"""Test-mode provider — the zero-config fallback shipped in every package.

When no model is configured (no Vertex project, no API key, no local runtime),
the platform still has to be demoable: story drafting, enrichment, agent flows.
This provider produces DETERMINISTIC, clearly-labeled output with no network,
no SDK, and no model weights — so the packaged desktop app works out of the box
and CI can exercise LLM-consuming endpoints hermetically.

It is prompt-shape aware: prompts that ask for a JSON array of user stories get
schema-compliant JSON (parseable by the Ideate drafting pipeline); prompts that
ask for a JSON object get a minimal object; everything else gets labeled text.
Every payload carries a "test-mode" marker so output is never mistaken for a
real model's.
"""
from __future__ import annotations

import json
import re
from typing import AsyncGenerator, Optional

MARKER = "test-mode"


def _keywords(text: str, limit: int = 6) -> list[str]:
    """Salient lowercase keywords from the prompt's requirements section."""
    words = re.findall(r"[A-Za-z][A-Za-z0-9-]{3,}", text or "")
    seen, out = set(), []
    stop = {"this", "that", "with", "from", "must", "return", "json", "array",
            "object", "keys", "each", "item", "string", "strings", "write",
            "below", "form", "want", "所有"}
    for w in words:
        lw = w.lower()
        if lw in stop or lw in seen:
            continue
        seen.add(lw)
        out.append(lw)
        if len(out) >= limit:
            break
    return out


def _wants_story_array(prompt: str) -> bool:
    p = (prompt or "").lower()
    return "json array" in p and ("stories" in p or "story" in p)


def _wants_json_object(prompt: str) -> bool:
    p = (prompt or "").lower()
    return "json" in p and "array" not in p


def _requirements_tail(prompt: str) -> str:
    """The user-content portion of a prompt (after a 'Requirements:'-ish header)."""
    m = re.search(r"(?:requirements|context|input)\s*:\s*\n(.*)", prompt or "",
                  re.IGNORECASE | re.DOTALL)
    return (m.group(1) if m else prompt or "").strip()


def stories_payload(prompt: str, count: int = 3) -> list[dict]:
    """Deterministic, schema-compliant user stories derived from the prompt."""
    tail = _requirements_tail(prompt)
    kws = _keywords(tail) or ["platform"]
    topic = " ".join(kws[:3])
    n = min(max(count, 1), 3)
    out = []
    for i in range(n):
        kw = kws[i % len(kws)]
        out.append({
            "title": f"[{MARKER}] Support {kw} ({i + 1})",
            "description": (f"As a user, I want {kw} handled based on the gathered "
                            f"requirements about {topic}, so that the workflow can be "
                            f"validated end to end without a configured model."),
            "acceptance_criteria": [
                f"Given the requirements, the {kw} behavior is implemented",
                "Output is reviewed and accepted by the requester",
                f"Generated by the built-in {MARKER} provider (configure a model for real drafts)",
            ],
            "priority": "Medium",
            "labels": [MARKER, kw][:2],
        })
    return out


class TestModeProvider:
    """Deterministic no-model provider (the packaged fallback)."""

    __test__ = False  # not a pytest class, despite the Test* name

    def __init__(self, model_name: Optional[str] = None,
                 system_instruction: Optional[str] = None):
        self.model_name = model_name or "builtin"
        self.system_instruction = system_instruction

    def generate(self, prompt: str) -> str:
        if _wants_story_array(prompt):
            m = re.search(r"up to (\d+)", prompt or "")
            count = int(m.group(1)) if m else 3
            return json.dumps(stories_payload(prompt, count), indent=2)
        if _wants_json_object(prompt):
            kws = _keywords(_requirements_tail(prompt))
            return json.dumps({"provider": MARKER, "summary": " ".join(kws[:5]),
                               "note": "Configure a model for real output."})
        tail = _requirements_tail(prompt)
        return (f"[{MARKER}] Deterministic response (no model configured).\n"
                f"Input digest: {' '.join(_keywords(tail))}\n"
                "Configure Vertex AI, an API key, or a local model "
                "(keel init local-model) for real output.")

    async def generate_async(self, prompt: str) -> str:
        return self.generate(prompt)

    async def generate_streaming(self, prompt: str) -> AsyncGenerator[str, None]:
        text = self.generate(prompt)
        for i in range(0, len(text), 64):
            yield text[i:i + 64]

    def get_name(self) -> str:
        return f"{MARKER}/{self.model_name}"
