"""Promote domain-authored skills back into the master skills registry.

The platform had a rich *downstream* path — registry skills flow into a domain
(``skill_trial_service.promote_trial`` → ``skills/validated/``) and superpowers
skills are injected as a baseline — but no *upstream* path. A skill authored
inside one domain's context-meta repo stayed there, invisible to every other
domain and to future scaffolds.

This module closes that loop:

1. :func:`discover_domain_skills` walks a domain repo and classifies every skill
   by **origin**, because "a skill the template didn't generate" is emphatically
   not the same as "a skill this domain authored". Getting this wrong would spam
   leads with promotion candidates they must not promote.
2. :func:`promote_to_registry` copies a promotable skill into the registry
   working tree, upserts ``registry.json``, and commits it on a dedicated
   branch — leaving the push/PR to a human, mirroring how the platform already
   treats the registry as a reviewed, shared artifact.

Nothing is pushed to a remote automatically.
"""
from __future__ import annotations

import hashlib
import json
import logging
import re
import shutil
import subprocess
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Callable, Optional

logger = logging.getLogger(__name__)

# ── Origins ─────────────────────────────────────────────────────────────────

#: Authored in this domain and not generated by the platform — promotable.
DOMAIN_AUTHORED = "domain-authored"
#: A superpowers skill forked for this domain (`keel domain fork-skill`) —
#: promotable as a variant/improvement.
DOMAIN_CUSTOMIZED = "domain-customized"
#: Injected superpowers baseline — already upstream, nothing to promote.
UPSTREAM_BASELINE = "upstream-baseline"
#: Rendered by the platform for this domain (persona/role/context skills).
#: Domain-specific by construction, so not reusable registry content.
PLATFORM_GENERATED = "platform-generated"
#: Copied in from the registry by `promote_trial` — already upstream.
REGISTRY_SOURCED = "registry-sourced"

PROMOTABLE_ORIGINS = frozenset({DOMAIN_AUTHORED, DOMAIN_CUSTOMIZED})

# ── Promotion kinds (vs the registry's current contents) ─────────────────────

NEW = "new"                 #: Not in the registry yet.
UPDATE = "update"           #: In the registry with different content.
IDENTICAL = "identical"     #: In the registry, byte-identical — nothing to do.

# ── Platform-generated skill names ──────────────────────────────────────────
#
# `keel domain gen-skills` / persona generation emit role skills and a
# per-domain context skill; `keel code onboard` emits `project-context`. These
# are renders of domain data, NOT reusable skills — promoting them to a shared
# registry would publish one domain's context to everybody.
_GENERATED_NAMES = frozenset({
    "project-context", "tech-lead-context",
    "dev", "qa", "ba", "sm", "domain",
})
_GENERATED_SUFFIXES = ("-domain-skill", "-domain-context")

# Directories inside a domain repo that hold skills, and how to read them.
_SKILL_ROOTS: tuple[tuple[str, tuple[str, ...]], ...] = (
    (".skills", ("superpowers",)),
    (".agents/skills", ("personas",)),
    ("skills/validated", ()),
)

_SAFE_NAME = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]*$")


@dataclass
class SkillCandidate:
    """One skill found in a domain repo, classified for promotion."""

    name: str
    path: Path
    origin: str
    location: str
    description: str = ""
    kind: str = NEW
    upstream_skill: str = ""
    reason: str = ""

    @property
    def promotable(self) -> bool:
        """Promotable = domain-owned content that would change the registry."""
        return self.origin in PROMOTABLE_ORIGINS and self.kind in (NEW, UPDATE)

    def to_dict(self) -> dict:
        return {
            "name": self.name, "path": str(self.path), "origin": self.origin,
            "location": self.location, "description": self.description,
            "kind": self.kind, "upstream_skill": self.upstream_skill,
            "promotable": self.promotable, "reason": self.reason,
        }


@dataclass
class PromotionResult:
    """Outcome of promoting one skill into the registry."""

    skill: str
    domain: str
    registry: Path
    dest: Path
    kind: str
    files: int
    branch: str = ""
    commit: str = ""
    committed: bool = False
    pushed: bool = False
    push_hint: str = ""
    gate: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "skill": self.skill, "domain": self.domain,
            "registry": str(self.registry), "dest": str(self.dest),
            "kind": self.kind, "files": self.files, "branch": self.branch,
            "commit": self.commit, "committed": self.committed,
            "pushed": self.pushed, "push_hint": self.push_hint,
            "gate": self.gate,
        }


class PromotionError(RuntimeError):
    """Raised when a promotion cannot proceed (not promotable, gate failed…)."""


# ── Helpers ─────────────────────────────────────────────────────────────────

def _is_generated(name: str) -> bool:
    return name in _GENERATED_NAMES or name.endswith(_GENERATED_SUFFIXES)


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


_TREE_SKIP_DIRS = frozenset({".git", "__pycache__", "node_modules"})
_TREE_SKIP_NAMES = frozenset({".DS_Store"})


def tree_hash(root: Path) -> dict[str, str]:
    """Map every meaningful file under ``root`` to its sha256.

    Used to tell an actual content change from a no-op re-promotion.
    """
    out: dict[str, str] = {}
    if not root.is_dir():
        return out
    stack = [root]
    while stack:
        current = stack.pop()
        try:
            entries = sorted(current.iterdir())
        except OSError:
            continue
        for entry in entries:
            if entry.is_symlink():
                continue
            if entry.is_dir():
                if entry.name not in _TREE_SKIP_DIRS:
                    stack.append(entry)
            elif entry.is_file() and entry.name not in _TREE_SKIP_NAMES:
                if entry.suffix in (".pyc", ".pyo"):
                    continue
                try:
                    out[entry.relative_to(root).as_posix()] = _sha256(entry)
                except OSError:
                    continue
    return out


def _frontmatter_description(skill_md: Path) -> str:
    """Read ``description:`` from a SKILL.md's YAML frontmatter."""
    try:
        text = skill_md.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""
    if not text.startswith("---"):
        return ""
    end = text.find("---", 3)
    block = text[3:end] if end > 0 else text[3:]
    m = re.search(r"^description:\s*(.*)$", block, re.MULTILINE)
    if not m:
        return ""
    value = m.group(1).strip()
    if value in (">-", ">", "|", "|-"):
        # Folded scalar — collect the indented continuation lines.
        lines: list[str] = []
        started = False
        for line in block.splitlines():
            if re.match(r"^description:\s*[>|]", line):
                started = True
                continue
            if started:
                if line.startswith((" ", "\t")) and line.strip():
                    lines.append(line.strip())
                elif line.strip():
                    break
        value = " ".join(lines)
    return value.strip().strip("\"'")[:300]


def _frontmatter_tags(skill_md: Path) -> list[str]:
    """Read an inline ``tags: [a, b]`` list from a SKILL.md's frontmatter."""
    try:
        text = skill_md.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return []
    if not text.startswith("---"):
        return []
    end = text.find("---", 3)
    block = text[3:end] if end > 0 else text[3:]
    m = re.search(r"^tags:\s*\[(.*?)\]", block, re.MULTILINE | re.DOTALL)
    if not m:
        return []
    return [t.strip().strip("\"'") for t in m.group(1).split(",") if t.strip()]


def load_registry_data(registry: Path) -> dict:
    """Load ``registry.json``, tolerating a missing/corrupt file."""
    path = Path(registry) / "registry.json"
    if not path.is_file():
        return {"skills": []}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return {"skills": []}
    if not isinstance(data, dict):
        return {"skills": []}
    data.setdefault("skills", [])
    return data


# ── Discovery + classification ──────────────────────────────────────────────

def _classify_origin(
    name: str, location: str, manifest_entry: Optional[dict]
) -> tuple[str, str, str]:
    """Return ``(origin, upstream_skill, reason)`` for one skill.

    Order matters. A forked skill IS recorded in the manifest with
    ``source: superpowers``, so the customization check must run before the
    baseline check or every fork would be misread as untouched upstream content.
    """
    if location == "skills/validated":
        return (REGISTRY_SOURCED, "",
                "installed from the registry by a skill trial promotion")

    if manifest_entry:
        if manifest_entry.get("customized") or manifest_entry.get("status") == "forked":
            return (DOMAIN_CUSTOMIZED,
                    str(manifest_entry.get("upstream_skill") or ""), "")
        if manifest_entry.get("source") == "superpowers":
            return (UPSTREAM_BASELINE, "",
                    "injected superpowers baseline — already upstream")

    if _is_generated(name):
        return (PLATFORM_GENERATED, "",
                "generated from this domain's data — not reusable across domains")

    return (DOMAIN_AUTHORED, "", "")


def _iter_skill_dirs(domain_repo: Path):
    """Yield ``(name, dir, location)`` for every skill folder in a domain repo."""
    seen: set[tuple[str, str]] = set()
    for location, skip in _SKILL_ROOTS:
        root = domain_repo / location
        if not root.is_dir():
            continue
        for entry in sorted(root.iterdir()):
            if not entry.is_dir() or entry.is_symlink():
                continue
            if entry.name in skip or not (entry / "SKILL.md").is_file():
                continue
            key = (location, entry.name)
            if key in seen:
                continue
            seen.add(key)
            yield entry.name, entry, location


def discover_domain_skills(
    domain_repo: Path, registry: Optional[Path] = None
) -> list[SkillCandidate]:
    """Classify every skill in a domain repo for upstream promotion.

    Returns *all* skills, promotable or not, each carrying its ``origin`` and a
    ``reason`` when excluded — so the UI can explain why a skill is not offered
    instead of silently hiding it.
    """
    from agentic_cli.kg.domain_skills import load_skills_manifest

    domain_repo = Path(domain_repo)
    manifest = (load_skills_manifest(domain_repo) or {}).get("skills") or {}

    registry_index: dict[str, dict[str, str]] = {}
    registry_names: set[str] = set()
    if registry:
        registry = Path(registry)
        registry_names = {
            str(s.get("name")) for s in load_registry_data(registry).get("skills", [])
            if s.get("name")
        }
        skills_root = registry / "skills"
        if skills_root.is_dir():
            for d in skills_root.iterdir():
                if d.is_dir():
                    registry_names.add(d.name)
                    registry_index[d.name] = tree_hash(d)

    candidates: list[SkillCandidate] = []
    for name, path, location in _iter_skill_dirs(domain_repo):
        origin, upstream, reason = _classify_origin(name, location, manifest.get(name))

        kind = NEW
        if name in registry_names:
            existing = registry_index.get(name)
            kind = IDENTICAL if existing and existing == tree_hash(path) else UPDATE
            if kind == IDENTICAL and not reason:
                reason = "byte-identical to the registry copy"

        candidates.append(SkillCandidate(
            name=name, path=path, origin=origin, location=location,
            description=_frontmatter_description(path / "SKILL.md"),
            kind=kind, upstream_skill=upstream, reason=reason,
        ))

    candidates.sort(key=lambda c: (not c.promotable, c.origin, c.name))
    return candidates


def discover_for_domain(
    domain: str, registry: Optional[Path] = None
) -> tuple[Path, list[SkillCandidate]]:
    """Resolve a domain's repo by convention, then classify its skills."""
    from agentic_cli.meta_repo.detector import detect_domain_meta_repo

    repo = detect_domain_meta_repo(domain)
    if repo is None:
        raise FileNotFoundError(
            f"No context-meta repo found for domain '{domain}'. "
            f"Create one with 'keel domain init {domain}'.")
    return repo, discover_domain_skills(repo, registry=registry)


# ── Gate ────────────────────────────────────────────────────────────────────

def default_gate(skill_dir: Path) -> tuple[bool, list[str]]:
    """Structural + security gate applied before anything reaches the registry.

    Deliberately the *minimum* bar: a parseable SKILL.md and no malicious
    pattern. Richer judgement (persona policy, LLM review, the full trial
    scorecard) is supplied by callers through ``gate`` — the dashboard passes
    its existing ``evaluate_trial`` scorecard.
    """
    notes: list[str] = []
    md = skill_dir / "SKILL.md"
    if not md.is_file():
        return False, ["SKILL.md is missing"]

    text = md.read_text(encoding="utf-8", errors="replace")
    if not text.startswith("---"):
        return False, ["SKILL.md needs YAML frontmatter (--- delimited)"]
    if not re.search(r"^name:\s*\S+", text, re.MULTILINE):
        return False, ["SKILL.md frontmatter is missing 'name'"]
    if not re.search(r"^description:\s*\S+", text, re.MULTILINE):
        return False, ["SKILL.md frontmatter is missing 'description'"]
    notes.append(f"structure ok ({len(text)} chars)")

    try:
        from agentic_cli.skill_security import scan_path

        result = scan_path(skill_dir, use_llm=False)
        verdict = str(result.get("verdict", "UNKNOWN"))
        notes.append(f"security: {verdict}")
        if verdict == "DO_NOT_INSTALL":
            return False, notes + ["security scan says DO_NOT_INSTALL"]
    except Exception as e:  # noqa: BLE001 - scanner optional
        notes.append(f"security: skipped ({str(e)[:60]})")

    return True, notes


# ── Git helpers (registry working tree) ─────────────────────────────────────

def _git(repo: Path, *args: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["git", "-C", str(repo), *args],
        capture_output=True, text=True,
    )


def is_git_repo(path: Path) -> bool:
    return (Path(path) / ".git").exists()


def branch_name(domain: str, skill: str) -> str:
    """``skill-promote/<domain>/<skill>`` — hierarchical, so promotions group.

    Components are sanitized individually: git accepts ``/`` in branch names but
    rejects empty components and ``..``.
    """
    parts = [re.sub(r"[^A-Za-z0-9._-]+", "-", p).strip("-.")
             for p in (domain, skill)]
    return "/".join(["skill-promote", *[p for p in parts if p]])


def _remote_url(repo: Path) -> str:
    res = _git(repo, "remote", "get-url", "origin")
    return res.stdout.strip() if res.returncode == 0 else ""


# ── Promotion ───────────────────────────────────────────────────────────────

def _upsert_registry_entry(
    registry: Path, name: str, description: str, tags: list[str], domain: str
) -> None:
    """Add or update a skill's ``registry.json`` entry, preserving extras.

    An update keeps whatever the registry already curated (``auto_detect``,
    ``mcp``, hand-tuned tags) and only refreshes the description — a promotion
    must never silently drop registry-side curation.
    """
    data = load_registry_data(registry)
    skills: list[dict] = list(data.get("skills") or [])
    domain_tag = f"domain:{domain}" if domain else ""

    existing = next((s for s in skills if s.get("name") == name), None)
    if existing is not None:
        if description:
            existing["description"] = description
        merged = list(dict.fromkeys([*(existing.get("tags") or []), *tags]))
        if domain_tag and domain_tag not in merged:
            merged.append(domain_tag)
        existing["tags"] = merged
    else:
        merged = list(dict.fromkeys(tags))
        if domain_tag:
            merged.append(domain_tag)
        skills.append({"name": name, "description": description, "tags": merged})

    data["skills"] = sorted(skills, key=lambda s: str(s.get("name", "")))
    (Path(registry) / "registry.json").write_text(
        json.dumps(data, indent=2) + "\n", encoding="utf-8")


def promote_to_registry(
    candidate: SkillCandidate,
    domain: str,
    registry: Path,
    *,
    domain_repo: Optional[Path] = None,
    gate: Optional[Callable[[Path], tuple[bool, list[str]]]] = None,
    commit: bool = True,
    push: bool = False,
    actor: Optional[str] = None,
    dry_run: bool = False,
) -> PromotionResult:
    """Copy a promotable domain skill into the registry and commit it.

    ``push`` is opt-in: writing to a shared registry's remote is an external,
    reviewed action, so by default this leaves a committed branch and returns
    the exact push command in :attr:`PromotionResult.push_hint`.
    """
    if not candidate.promotable:
        raise PromotionError(
            f"'{candidate.name}' is not promotable (origin={candidate.origin}, "
            f"kind={candidate.kind})"
            + (f": {candidate.reason}" if candidate.reason else ""))
    if not _SAFE_NAME.match(candidate.name):
        raise PromotionError(f"Unsafe skill name: {candidate.name!r}")

    registry = Path(registry)
    dest = registry / "skills" / candidate.name

    checks = gate(candidate.path) if gate else default_gate(candidate.path)
    passed, notes = checks
    if not passed:
        raise PromotionError(
            f"'{candidate.name}' failed the promotion gate: " + "; ".join(notes))

    file_count = len(tree_hash(candidate.path))
    result = PromotionResult(
        skill=candidate.name, domain=domain, registry=registry, dest=dest,
        kind=candidate.kind, files=file_count, gate=notes,
    )

    if dry_run:
        result.push_hint = "(dry run — nothing written)"
        return result

    # Copy the whole skill folder: SKILL.md plus scripts/, references/, evals/.
    dest.parent.mkdir(parents=True, exist_ok=True)
    if dest.exists():
        shutil.rmtree(dest)
    shutil.copytree(candidate.path, dest,
                    ignore=shutil.ignore_patterns(".git", "__pycache__", "*.pyc",
                                                  ".DS_Store"))

    _upsert_registry_entry(
        registry, candidate.name, candidate.description,
        _frontmatter_tags(candidate.path / "SKILL.md"), domain,
    )

    if commit and is_git_repo(registry):
        result.branch = branch_name(domain, candidate.name)
        _commit_promotion(registry, result, candidate, domain)
        if push and result.committed:
            res = _git(registry, "push", "-u", "origin", result.branch)
            result.pushed = res.returncode == 0
            if not result.pushed:
                logger.warning("Push failed: %s", res.stderr.strip()[:200])
        if not result.pushed and result.branch:
            result.push_hint = (
                f"git -C {registry} push -u origin {result.branch}")
    elif commit:
        result.push_hint = (
            f"{registry} is not a git repository — files were written in place")

    _audit(result, candidate, domain, domain_repo, actor)
    return result


def _commit_promotion(
    registry: Path, result: PromotionResult,
    candidate: SkillCandidate, domain: str,
) -> None:
    """Create the promotion branch and commit the staged skill."""
    # Start from the current HEAD; reuse the branch if a previous promotion of
    # the same skill left one behind.
    res = _git(registry, "checkout", "-B", result.branch)
    if res.returncode != 0:
        logger.warning("Could not create branch %s: %s",
                       result.branch, res.stderr.strip()[:200])
        return

    _git(registry, "add", f"skills/{candidate.name}", "registry.json")
    verb = "Add" if candidate.kind == NEW else "Update"
    message = (
        f"{verb} skill '{candidate.name}' promoted from {domain}\n\n"
        f"Origin: {candidate.origin}\n"
        f"Source: {candidate.path}\n"
        + (f"Upstream skill: {candidate.upstream_skill}\n"
           if candidate.upstream_skill else "")
        + f"Promoted by: keel skill upstream promote\n"
    )
    res = _git(registry, "commit", "-m", message)
    if res.returncode == 0:
        result.committed = True
        sha = _git(registry, "rev-parse", "--short", "HEAD")
        result.commit = sha.stdout.strip() if sha.returncode == 0 else ""
    elif "nothing to commit" in (res.stdout + res.stderr).lower():
        result.committed = False
        logger.info("Nothing to commit for %s", candidate.name)
    else:
        logger.warning("Commit failed: %s", (res.stderr or res.stdout).strip()[:200])


def _audit(
    result: PromotionResult, candidate: SkillCandidate, domain: str,
    domain_repo: Optional[Path], actor: Optional[str],
) -> None:
    """Record the promotion centrally and in the domain's evolution log."""
    try:
        from agentic_cli.tracker import record_action

        record_action("skill", "promote_upstream", entity_type="skill",
                      entity_id=candidate.name, actor=actor,
                      details={"domain": domain, "origin": candidate.origin,
                               "kind": candidate.kind,
                               "branch": result.branch,
                               "committed": result.committed,
                               "pushed": result.pushed})
    except Exception:  # noqa: BLE001 - auditing must never break a promotion
        pass

    if domain_repo:
        try:
            from agentic_cli.kg.domain_skills import log_skill_event

            log_skill_event(Path(domain_repo), candidate.name, "contributed", {
                "registry": str(result.registry),
                "kind": candidate.kind,
                "branch": result.branch,
                "committed": result.committed,
                "at": datetime.now(timezone.utc).isoformat(),
            })
        except Exception:  # noqa: BLE001
            pass


__all__ = [
    "DOMAIN_AUTHORED", "DOMAIN_CUSTOMIZED", "UPSTREAM_BASELINE",
    "PLATFORM_GENERATED", "REGISTRY_SOURCED", "PROMOTABLE_ORIGINS",
    "NEW", "UPDATE", "IDENTICAL",
    "SkillCandidate", "PromotionResult", "PromotionError",
    "discover_domain_skills", "discover_for_domain", "promote_to_registry",
    "default_gate", "tree_hash", "load_registry_data", "branch_name",
    "is_git_repo",
]
