"""Build rich project context documents for KG ingestion.

This module generates structured context documents from ProjectAnalysis
data produced during `agent-cli code onboard`. The output is suitable for:
  1. Direct LightRAG insertion (semantic search)
  2. Full KG ingestion with entity extraction (Neo4j)
  3. IDE agent consumption via .skills/ directory
  4. LLM-based code-to-requirement linking

Three document types are produced:
  - kg-code-context.md        — code structure + Graphify analysis (per repo)
  - kg-<domain>-context.md    — business/requirements context (per domain, e.g. kg-cwow-facility-context.md)
  - SKILL.md patch            — context-first workflow instructions for coding agents

Naming rationale:
  Code context  → generated by `code onboard --kg [--link-kg]`, linked to KG requirements
  Business context → generated by `kg ingest submit --domain <slug>`, ingested into Neo4j (Document nodes)
  Neo4j is the final unified destination where Code:: ←→ Document relationships are drawn.
"""

import json
from pathlib import Path
from typing import Any, Optional
import re

from rich.console import Console
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

from agentic_cli.config import CLI_NAME
from agentic_cli.analyzer.detector import ProjectAnalysis

console = Console()


def link_code_to_requirements(
    project_path: Path,
    domain_slug: str,
    context_path: Optional[Path] = None,
) -> dict[str, Any]:
    """Link code context to KG requirements using LLM.

    Queries Neo4j for domain requirements, analyzes kg-code-context.md with Vertex AI,
    and creates Code:* → Document:* relationships (IMPLEMENTS, REFERENCES, TESTS).

    Args:
        project_path: Absolute path to the project root.
        domain_slug: Domain slug (e.g., cwow-facility).
        context_path: Path to kg-code-context.md (default: .skills/project-context/kg-code-context.md).

    Returns:
        Dict with linking results: links_created, errors, etc.
    """
    from agentic_cli.kg.config import KGConfig
    from agentic_cli.kg.neo4j_client import Neo4jClient

    # Default context path
    if context_path is None:
        context_path = project_path / ".skills" / "project-context" / "kg-code-context.md"

    if not context_path.exists():
        return {
            "success": False,
            "error": f"Context file not found: {context_path}",
            "links_created": 0,
        }

    # Load KG config
    kg_config = KGConfig.load()
    if not kg_config.is_neo4j_configured():
        return {
            "success": False,
            "error": "Neo4j is not configured",
            "links_created": 0,
        }

    # Read code context
    code_context = context_path.read_text()

    # Run graphify to generate detailed code structure if not already present
    graphify_json_path = project_path / "graphify-out" / "graph.json"
    if not graphify_json_path.exists():
        console.print(f"[dim]Running graphify to generate code structure analysis...[/dim]")
        try:
            import subprocess
            import os
            
            # Graphify uses Google Cloud ADC (Application Default Credentials)
            # which is already configured for Vertex AI
            # No API key needed - it uses gcloud auth or GOOGLE_APPLICATION_CREDENTIALS
            result = subprocess.run(
                ["graphify", str(project_path), "--no-viz"],
                capture_output=True,
                text=True,
                timeout=300,  # 5 minute timeout
            )
            if result.returncode != 0:
                console.print(f"[yellow]⚠ Graphify failed: {result.stderr}[/yellow]")
                console.print(f"[dim]Proceeding with basic code context[/dim]")
            else:
                console.print(f"[green]✓ Graphify analysis generated[/green]")
        except Exception as e:
            console.print(f"[yellow]⚠ Graphify not available or failed: {e}[/yellow]")
            console.print(f"[dim]Proceeding with basic code context[/dim]")
    else:
        console.print(f"[dim]Using existing graphify.json[/dim]")

    # If graphify.json exists, enhance code context with it
    if graphify_json_path.exists():
        try:
            import json
            graphify_data = json.loads(graphify_json_path.read_text())
            graphify_summary = f"\n\n## Code Structure (Graphify)\n"
            graphify_summary += f"- Nodes: {len(graphify_data.get('nodes', []))}\n"
            graphify_summary += f"- Edges: {len(graphify_data.get('edges', []))}\n"
            graphify_summary += f"- Communities: {len(graphify_data.get('communities', {}))}\n"
            code_context += graphify_summary
            console.print(f"[dim]Enhanced code context with graphify analysis[/dim]")
        except Exception as e:
            console.print(f"[yellow]⚠ Failed to read graphify.json: {e}[/dim]")

    # Query KG for domain requirements
    neo4j = Neo4jClient(config=kg_config)

    # Get Document nodes for this domain
    # Try multiple matching strategies
    query = """
    MATCH (d:Document)
    WHERE d.domain = $domain_slug OR d.name CONTAINS $domain_slug OR d.id CONTAINS $domain_slug
    RETURN d.name AS name, d.content AS content, d.id AS id
    LIMIT 50
    """
    neo4j.connect()
    requirements = neo4j.execute_cypher(query, {"domain_slug": domain_slug})
    neo4j.close()

    console.print(f"[dim]Query 1 (exact domain match): Found {len(requirements)} requirements[/dim]")

    # If no exact match, try broader patterns
    if not requirements:
        # Try matching "CWOV" for cwow-facility
        broader_query = """
        MATCH (d:Document)
        WHERE d.name CONTAINS 'CWOV' OR d.name CONTAINS 'Facility'
        RETURN d.name AS name, d.content AS content, d.id AS id
        LIMIT 50
        """
        neo4j.connect()
        requirements = neo4j.execute_cypher(broader_query, {})
        neo4j.close()
        console.print(f"[dim]Query 2 (broader CWOV/Facility match): Found {len(requirements)} requirements[/dim]")

    console.print(f"[dim]Domain slug: {domain_slug}[/dim]")
    
    if not requirements:
        # Try a broader query to see what Document nodes exist
        debug_query = """
        MATCH (d:Document)
        RETURN d.name AS name, d.domain AS domain, d.id AS id
        LIMIT 10
        """
        neo4j.connect()
        debug_results = neo4j.execute_cypher(debug_query, {})
        neo4j.close()
        
        console.print(f"[dim]Debug: Sample Document nodes in KG:[/dim]")
        for r in debug_results:
            console.print(f"[dim]  - {r.get('name', 'N/A')} (domain: {r.get('domain', 'N/A')})[/dim]")

    if not requirements:
        return {
            "success": False,
            "error": f"No requirements found for domain: {domain_slug}",
            "links_created": 0,
        }

    console.print(f"[dim]Found {len(requirements)} requirements in KG[/dim]")

    # Use Vertex AI to link code to requirements
    try:
        from vertexai.generative_models import GenerativeModel

        model = GenerativeModel(
            "gemini-2.5-flash-lite",
            system_instruction="""You are a code-to-requirement linker. Analyze code context and identify which requirements each code element implements, references, or tests.

Output format (JSON):
{
  "links": [
    {
      "code_element": "file/function/class name",
      "requirement_id": "requirement ID or name",
      "relationship_type": "IMPLEMENTS|REFERENCES|TESTS",
      "confidence": 0.0-1.0,
      "reasoning": "brief explanation"
    }
  ]
}

Only include links with confidence >= 0.7. Be precise and conservative.
""",
        )

        # Build prompt
        requirements_text = "\n".join(
            [f"- {r['name']}: {r.get('content', '')[:200]}" for r in requirements[:20]]
        )

        prompt = f"""Code Context:
{code_context[:5000]}

Requirements:
{requirements_text}

Identify which code elements implement, reference, or test which requirements. Return JSON output only."""

        response = model.generate_content(prompt)
        result_text = response.text.strip()

        # Parse JSON response
        # Handle potential markdown code blocks
        if "```json" in result_text:
            result_text = result_text.split("```json")[1].split("```")[0].strip()
        elif "```" in result_text:
            result_text = result_text.split("```")[1].split("```")[0].strip()

        import json
        link_data = json.loads(result_text)
        links = link_data.get("links", [])

        console.print(f"[dim]LLM identified {len(links)} potential links[/dim]")

        # Create relationships in Neo4j
        links_created = 0
        neo4j.connect()
        for link in links:
            if link.get("confidence", 0) < 0.7:
                continue

            code_element = link["code_element"]
            requirement_name = link["requirement_id"]
            rel_type = link["relationship_type"]

            # Create or find Code node
            code_query = """
            MERGE (c:Code {name: $code_name, project: $project})
            SET c.project_path = $project_path
            RETURN c
            """
            neo4j.execute_cypher(
                code_query,
                {
                    "code_name": code_element,
                    "project": project_path.name,
                    "project_path": str(project_path),
                },
            )

            # Create relationship
            rel_query = f"""
            MATCH (c:Code {{name: $code_name, project: $project}})
            MATCH (d:Document {{name: $req_name}})
            MERGE (c)-[r:{rel_type}]->(d)
            SET r.confidence = $conf, r.reasoning = $reasoning
            RETURN r
            """
            neo4j.execute_cypher(
                rel_query,
                {
                    "code_name": code_element,
                    "project": project_path.name,
                    "req_name": requirement_name,
                    "conf": link.get("confidence", 0.7),
                    "reasoning": link.get("reasoning", ""),
                },
            )

            links_created += 1
        neo4j.close()

        console.print(f"[green]✓ Created {links_created} code-requirement links[/green]")

        return {
            "success": True,
            "links_created": links_created,
            "total_identified": len(links),
        }

    except Exception as e:
        console.print(f"[yellow]⚠ LLM linking failed: {e}[/yellow]")
        return {
            "success": False,
            "error": str(e),
            "links_created": 0,
        }



def build_kg_context_document(
    project_path: Path,
    analysis: ProjectAnalysis,
    installed_skills: list[str],
    suggested_skills: Optional[list[str]] = None,
) -> str:
    """Build a rich markdown context document from project analysis.

    This document is designed for ingestion into a knowledge graph (LightRAG
    or Neo4j). It contains structured information about the project's
    architecture, tech stack, conventions, and integration points.

    Args:
        project_path: Absolute path to the project root.
        analysis: ProjectAnalysis from the analyzer/detector.
        installed_skills: Names of skills installed during onboard.
        suggested_skills: Names of suggested (but not installed) skills.

    Returns:
        Markdown string suitable for KG ingestion.
    """
    project_name = project_path.name
    suggested_skills = suggested_skills or []
    timestamp = datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")

    # --- helpers --------------------------------------------------------
    def _bullet_list(items: list[str], limit: int = 30) -> str:
        if not items:
            return "_None detected_\n"
        lines = [f"- {item}" for item in items[:limit]]
        if len(items) > limit:
            lines.append(f"- _... and {len(items) - limit} more_")
        return "\n".join(lines) + "\n"

    def _dep_list(deps: list[str], raw: dict[str, str], limit: int = 40) -> str:
        if not deps:
            return "_No dependencies detected_\n"
        lines = []
        for dep in deps[:limit]:
            ver = raw.get(dep, "")
            lines.append(f"- `{dep}`" + (f" ({ver})" if ver else ""))
        if len(deps) > limit:
            lines.append(f"- _... and {len(deps) - limit} more_")
        return "\n".join(lines) + "\n"

    # --- sections -------------------------------------------------------
    sections: list[str] = []

    # Header
    sections.append(f"# Project Context: {project_name}\n")
    sections.append(
        f"> Auto-generated by `agent-cli code onboard --kg` on {timestamp}.\n"
        f"> **Code context** (kg-code-context.md) — ingested into LightRAG (semantic search) then Neo4j (Code:: nodes).\n"
        f"> For business/requirements context see kg-<domain>-context.md (generated by `dva kg ingest submit --domain <slug>`).\n"
    )

    # Tech Stack
    sections.append("## Technology Stack\n")
    rows = [
        ("Languages", ", ".join(analysis.languages) if analysis.languages else "Unknown"),
        ("Frameworks", ", ".join(analysis.frameworks) if analysis.frameworks else "None detected"),
        ("Build Tools", ", ".join(analysis.build_tools) if analysis.build_tools else "None detected"),
        ("Test Frameworks", ", ".join(analysis.test_frameworks) if analysis.test_frameworks else "None detected"),
        ("Databases", ", ".join(analysis.databases) if analysis.databases else "None detected"),
        ("API Types", ", ".join(analysis.api_types) if analysis.api_types else "None detected"),
        ("CI/CD", ", ".join(analysis.ci_cd) if analysis.ci_cd else "None detected"),
        ("Docker", "Yes" if analysis.has_docker else "No"),
    ]
    sections.append("| Aspect | Detail |")
    sections.append("|--------|--------|")
    for label, value in rows:
        sections.append(f"| **{label}** | {value} |")
    sections.append("")

    # Architecture — Module Structure
    sections.append("## Architecture — Module Structure\n")
    if analysis.module_structure:
        sections.append(_bullet_list(analysis.module_structure, limit=25))
    else:
        sections.append("_No top-level modules detected._\n")

    # Entry Points
    sections.append("## Entry Points\n")
    if analysis.entry_points:
        sections.append(_bullet_list(analysis.entry_points))
    else:
        sections.append("_No entry points detected._\n")

    # Source Code Patterns
    if analysis.source_patterns:
        sections.append("## Source Code Patterns\n")
        sections.append(_bullet_list(analysis.source_patterns))

    # Dependencies
    sections.append(f"## Dependencies ({len(analysis.dependencies)} total)\n")
    sections.append(
        _dep_list(analysis.dependencies, analysis.raw_dependencies, limit=40)
    )

    # Integration Points
    integrations: list[str] = []
    if analysis.databases:
        integrations.extend(f"Database: {db}" for db in analysis.databases)
    if analysis.api_types:
        integrations.extend(f"API: {api}" for api in analysis.api_types)
    if analysis.ci_cd:
        integrations.extend(f"CI/CD: {ci}" for ci in analysis.ci_cd)
    if analysis.has_docker:
        integrations.append("Containerization: Docker")

    if integrations:
        sections.append("## Integration Points\n")
        sections.append(_bullet_list(integrations))

    # Installed Skills
    sections.append(f"## Installed Skills ({len(installed_skills)})\n")
    sections.append(_bullet_list(installed_skills))

    # Suggested Skills
    if suggested_skills:
        sections.append(f"## Suggested Skills ({len(suggested_skills)})\n")
        sections.append(_bullet_list(suggested_skills))

    # Project Files Detected
    detected_files = [f for f, present in analysis.project_files.items() if present]
    if detected_files:
        sections.append("## Key Project Files\n")
        sections.append(_bullet_list(sorted(detected_files)))

    return "\n".join(sections)


def build_skill_kg_instructions(project_name: str) -> str:
    """Build the KG context-first workflow instructions for SKILL.md.

    These instructions are appended to the project-context SKILL.md so that
    any coding agent (Windsurf, Claude, OpenCode, Cursor) knows to query the
    Knowledge Graph before starting work.

    Args:
        project_name: Name of the project (used in tool call examples).

    Returns:
        Markdown string to append to SKILL.md.
    """
    return f"""
## Context-First Workflow (Knowledge Graph)

This project's context has been ingested into the Knowledge Graph.
**Before starting any coding task**, follow these steps:

1. **Get project overview** — call `get_project_context(project="{project_name}")`
2. **Search for relevant context** — call `search_business_context(query="<your task description>")`
3. **Review results** before writing or modifying code
4. **When unsure about patterns** — call `search_business_context(query="conventions for <topic>")`

> These tools are provided by the KG MCP server.
> If the tools are not available, read this SKILL.md for baseline context.
"""


def save_kg_context(
    project_path: Path,
    analysis: ProjectAnalysis,
    installed_skills: list[str],
    suggested_skills: Optional[list[str]] = None,
) -> Path:
    """Generate and save kg-code-context.md to the project's .skills/ directory.

    Naming convention:
      - kg-code-context.md   → code structure/stack context (this file, with or without Graphify)
      - kg-<domain>-context.md → business/requirements context per domain (generated separately)

    Args:
        project_path: Absolute path to the project root.
        analysis: ProjectAnalysis from the analyzer/detector.
        installed_skills: Names of installed skills.
        suggested_skills: Names of suggested skills.

    Returns:
        Path to the saved kg-code-context.md file.
    """
    content = build_kg_context_document(
        project_path, analysis, installed_skills, suggested_skills
    )
    skill_dir = project_path / ".skills" / "project-context"
    skill_dir.mkdir(parents=True, exist_ok=True)

    context_path = skill_dir / "kg-code-context.md"
    context_path.write_text(content)
    return context_path


def save_kg_business_context(
    project_path: Path,
    domain_slug: str,
    content: str,
) -> Path:
    """Save business/requirements context as kg-<domain>-context.md.

    This file is the counterpart to kg-code-context.md — it contains
    Confluence OneViews, PDF requirements, and domain specs ingested
    separately and linked to code context in Neo4j.

    Args:
        project_path: Absolute path to the project root (or domain workspace).
        domain_slug: Domain identifier e.g. 'cwow-facility', 'cwow-patient'.
        content: Markdown content from Confluence/PDF ingestion.

    Returns:
        Path to the saved kg-<domain>-context.md file.
    """
    skill_dir = project_path / ".skills" / "project-context"
    skill_dir.mkdir(parents=True, exist_ok=True)

    context_path = skill_dir / f"kg-{domain_slug}-context.md"
    context_path.write_text(content)
    return context_path


def patch_skill_md_with_kg_instructions(project_path: Path) -> bool:
    """Append KG instructions to the project-context SKILL.md if not already present.

    Args:
        project_path: Absolute path to the project root.

    Returns:
        True if SKILL.md was updated, False if already patched or missing.
    """
    skill_md = project_path / ".skills" / "project-context" / "SKILL.md"
    if not skill_md.exists():
        return False

    existing = skill_md.read_text()
    marker = "## Context-First Workflow (Knowledge Graph)"
    if marker in existing:
        return False  # already patched

    instructions = build_skill_kg_instructions(project_path.name)
    skill_md.write_text(existing.rstrip() + "\n" + instructions)
    return True


def register_kg_data_source(
    project_path: Path,
    analysis: ProjectAnalysis,
) -> dict[str, Any]:
    """Register the project's context directory as a data source.

    Adds an entry to ``~/.agent-cli-agentic/config.json`` → ``data.sources[]``
    so that ``agent-cli kg ingest submit --source onboard-<project>`` works.

    The source is idempotent — re-onboarding overwrites the existing entry.

    Args:
        project_path: Absolute path to the project root.
        analysis: ProjectAnalysis (used for tags).

    Returns:
        The data-source dict that was written.
    """
    config_dir = Path.home() / ".agent-cli-agentic"
    config_file = config_dir / "config.json"

    # Load existing config
    config: dict[str, Any] = {}
    if config_file.exists():
        try:
            config = json.loads(config_file.read_text())
        except (json.JSONDecodeError, OSError):
            pass

    # Ensure data section
    if "data" not in config:
        config["data"] = {"globals": {"gcs": {}, "confluence": {}}, "sources": []}
    if "sources" not in config["data"]:
        config["data"]["sources"] = []

    project_name = project_path.name
    source_name = f"onboard-{project_name}"
    context_dir = str(project_path / ".skills" / "project-context")

    # Build tags from analysis
    tags = ["onboard", "project-context"]
    tags.extend(analysis.languages[:3])
    tags.extend(analysis.frameworks[:3])

    new_source = {
        "name": source_name,
        "type": "doc",
        "location": context_dir,
        "description": f"Auto-generated project context from agent-cli code onboard for {project_name}",
        "tags": [t.lower() for t in tags],
        "project": project_name,
        "kg_status": "registered",
        "created_at": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
    }

    # Idempotent: remove existing entry with same name
    config["data"]["sources"] = [
        s for s in config["data"]["sources"] if s.get("name") != source_name
    ]
    config["data"]["sources"].append(new_source)

    # Save
    config_dir.mkdir(parents=True, exist_ok=True)
    config_file.write_text(json.dumps(config, indent=2))

    return new_source


def ingest_context_to_lightrag(
    context_path: Path,
    project_name: str,
    lightrag_url: str = "http://localhost:8001",
    timeout: float = 30.0,
) -> dict[str, Any]:
    """Insert the kg-context.md document into LightRAG for semantic search.

    This is the *light mode* ingestion — text only, no entity extraction.

    Args:
        context_path: Path to kg-context.md.
        project_name: Project name (used in metadata).
        lightrag_url: Base URL of the LightRAG server.
        timeout: Request timeout in seconds.

    Returns:
        LightRAG insert result dict.

    Raises:
        FileNotFoundError: If context_path doesn't exist.
        ImportError: If httpx is not installed.
        Exception: On connection or insert errors.
    """
    if not context_path.exists():
        raise FileNotFoundError(f"Context file not found: {context_path}")

    from agentic_cli.kg.lightrag_client import LightRAGClient

    text = context_path.read_text()
    # Derive doc_type from filename: kg-code-context.md → code_context, kg-<domain>-context.md → business_context
    name = context_path.name
    if name == "kg-code-context.md":
        doc_type = "code_context"
    elif name.startswith("kg-") and name.endswith("-context.md"):
        doc_type = "business_context"
    else:
        doc_type = "project_context"
    metadata = {
        "source": "agent-cli-code-onboard",
        "project": project_name,
        "doc_type": doc_type,
        "filename": name,
        "filepath": str(context_path),
    }

    client = LightRAGClient(base_url=lightrag_url, timeout=timeout)
    try:
        return client.insert(text, metadata)
    finally:
        client.close()


def run_kg_context_pipeline(
    project_path: Path,
    analysis: ProjectAnalysis,
    installed_skills: list[str],
    suggested_skills: Optional[list[str]] = None,
    ingest: bool = True,
    lightrag_url: Optional[str] = None,
) -> dict[str, Any]:
    """Run the full KG context pipeline: build, save, register, ingest.

    This is the main entry point called from ``agent-cli code onboard --kg``.

    Args:
        project_path: Absolute path to the project root.
        analysis: ProjectAnalysis from the analyzer.
        installed_skills: Names of installed skills.
        suggested_skills: Names of suggested skills.
        ingest: If True, also ingest into the configured KG provider.
        lightrag_url: LightRAG server URL (deprecated, uses KGConfig instead).

    Returns:
        Result dict with keys: context_path, source, skill_patched,
        ingested, ingest_result.
    """
    from agentic_cli.kg.config import KGConfig
    
    # Load KG config to determine provider
    kg_config = KGConfig.load()
    provider = kg_config.provider
    
    result: dict[str, Any] = {
        "context_path": None,
        "source": None,
        "skill_patched": False,
        "ingested": False,
        "ingest_result": None,
        "errors": [],
        "provider": provider,
    }

    # 1. Build and save kg-context.md
    context_path = save_kg_context(
        project_path, analysis, installed_skills, suggested_skills
    )
    result["context_path"] = str(context_path)

    # 2. Patch SKILL.md with KG instructions
    result["skill_patched"] = patch_skill_md_with_kg_instructions(project_path)

    # 3. Register as data source
    try:
        source = register_kg_data_source(project_path, analysis)
        result["source"] = source
    except Exception as e:
        result["errors"].append(f"Data source registration failed: {e}")

    # 4. Ingest into configured KG provider (if requested)
    if ingest:
        try:
            if provider == "neo4j":
                # Neo4j ingestion - register data source only, actual ingestion happens via kg ingest pipeline
                # Use register_kg_data_source which is already defined in this file
                source = register_kg_data_source(project_path, analysis)
                result["source"] = source
                result["ingested"] = True
                console.print(f"[green]✓[/green] Data source registered for Neo4j ingestion")
                console.print(f"[dim]Run '{CLI_NAME} kg ingest submit --source onboard-{project_path.name}' to complete ingestion[/dim]")
            elif provider == "lightrag":
                # LightRAG ingestion
                lightrag_url = lightrag_url or kg_config.lightrag_url
                ingest_result = ingest_context_to_lightrag(
                    context_path,
                    project_path.name,
                    lightrag_url=lightrag_url,
                )
                result["ingested"] = True
                result["ingest_result"] = ingest_result
            else:
                result["errors"].append(f"Unsupported KG provider: {provider}")
        except ImportError as e:
            result["errors"].append(f"{provider} client not available: {e}")
        except Exception as e:
            result["errors"].append(f"{provider} ingestion failed: {e}")

    return result
