"""Build rich project context documents for KG ingestion.

This module generates structured context documents from ProjectAnalysis
data produced during `agent-cli code onboard`. The output is suitable for:
  1. Direct LightRAG insertion (semantic search)
  2. Full KG ingestion with entity extraction (Neo4j)
  3. IDE agent consumption via .skills/ directory

Three document types are produced:
  - kg-code-context.md        — code structure + Graphify analysis (per repo)
  - kg-<domain>-context.md    — business/requirements context (per domain, e.g. kg-cwow-facility-context.md)
  - SKILL.md patch            — context-first workflow instructions for coding agents

Naming rationale:
  Code context  → generated by `code onboard --kg [--graphify]`, ingested into LightRAG then Neo4j (Code:: nodes)
  Business context → generated by `kg ingest submit --domain <slug>`, ingested into Neo4j (Document nodes)
  Neo4j is the final unified destination where Code:: ←→ Document relationships are drawn.
"""

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

from agentic_cli.analyzer.detector import ProjectAnalysis


def build_kg_context_document(
    project_path: Path,
    analysis: ProjectAnalysis,
    installed_skills: list[str],
    suggested_skills: Optional[list[str]] = None,
) -> str:
    """Build a rich markdown context document from project analysis.

    This document is designed for ingestion into a knowledge graph (LightRAG
    or Neo4j). It contains structured information about the project's
    architecture, tech stack, conventions, and integration points.

    Args:
        project_path: Absolute path to the project root.
        analysis: ProjectAnalysis from the analyzer/detector.
        installed_skills: Names of skills installed during onboard.
        suggested_skills: Names of suggested (but not installed) skills.

    Returns:
        Markdown string suitable for KG ingestion.
    """
    project_name = project_path.name
    suggested_skills = suggested_skills or []
    timestamp = datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")

    # --- helpers --------------------------------------------------------
    def _bullet_list(items: list[str], limit: int = 30) -> str:
        if not items:
            return "_None detected_\n"
        lines = [f"- {item}" for item in items[:limit]]
        if len(items) > limit:
            lines.append(f"- _... and {len(items) - limit} more_")
        return "\n".join(lines) + "\n"

    def _dep_list(deps: list[str], raw: dict[str, str], limit: int = 40) -> str:
        if not deps:
            return "_No dependencies detected_\n"
        lines = []
        for dep in deps[:limit]:
            ver = raw.get(dep, "")
            lines.append(f"- `{dep}`" + (f" ({ver})" if ver else ""))
        if len(deps) > limit:
            lines.append(f"- _... and {len(deps) - limit} more_")
        return "\n".join(lines) + "\n"

    # --- sections -------------------------------------------------------
    sections: list[str] = []

    # Header
    sections.append(f"# Project Context: {project_name}\n")
    sections.append(
        f"> Auto-generated by `agent-cli code onboard --kg` on {timestamp}.\n"
        f"> **Code context** (kg-code-context.md) — ingested into LightRAG (semantic search) then Neo4j (Code:: nodes).\n"
        f"> For business/requirements context see kg-<domain>-context.md (generated by `dva kg ingest submit --domain <slug>`).\n"
    )

    # Tech Stack
    sections.append("## Technology Stack\n")
    rows = [
        ("Languages", ", ".join(analysis.languages) if analysis.languages else "Unknown"),
        ("Frameworks", ", ".join(analysis.frameworks) if analysis.frameworks else "None detected"),
        ("Build Tools", ", ".join(analysis.build_tools) if analysis.build_tools else "None detected"),
        ("Test Frameworks", ", ".join(analysis.test_frameworks) if analysis.test_frameworks else "None detected"),
        ("Databases", ", ".join(analysis.databases) if analysis.databases else "None detected"),
        ("API Types", ", ".join(analysis.api_types) if analysis.api_types else "None detected"),
        ("CI/CD", ", ".join(analysis.ci_cd) if analysis.ci_cd else "None detected"),
        ("Docker", "Yes" if analysis.has_docker else "No"),
    ]
    sections.append("| Aspect | Detail |")
    sections.append("|--------|--------|")
    for label, value in rows:
        sections.append(f"| **{label}** | {value} |")
    sections.append("")

    # Architecture — Module Structure
    sections.append("## Architecture — Module Structure\n")
    if analysis.module_structure:
        sections.append(_bullet_list(analysis.module_structure, limit=25))
    else:
        sections.append("_No top-level modules detected._\n")

    # Entry Points
    sections.append("## Entry Points\n")
    if analysis.entry_points:
        sections.append(_bullet_list(analysis.entry_points))
    else:
        sections.append("_No entry points detected._\n")

    # Source Code Patterns
    if analysis.source_patterns:
        sections.append("## Source Code Patterns\n")
        sections.append(_bullet_list(analysis.source_patterns))

    # Dependencies
    sections.append(f"## Dependencies ({len(analysis.dependencies)} total)\n")
    sections.append(
        _dep_list(analysis.dependencies, analysis.raw_dependencies, limit=40)
    )

    # Integration Points
    integrations: list[str] = []
    if analysis.databases:
        integrations.extend(f"Database: {db}" for db in analysis.databases)
    if analysis.api_types:
        integrations.extend(f"API: {api}" for api in analysis.api_types)
    if analysis.ci_cd:
        integrations.extend(f"CI/CD: {ci}" for ci in analysis.ci_cd)
    if analysis.has_docker:
        integrations.append("Containerization: Docker")

    if integrations:
        sections.append("## Integration Points\n")
        sections.append(_bullet_list(integrations))

    # Installed Skills
    sections.append(f"## Installed Skills ({len(installed_skills)})\n")
    sections.append(_bullet_list(installed_skills))

    # Suggested Skills
    if suggested_skills:
        sections.append(f"## Suggested Skills ({len(suggested_skills)})\n")
        sections.append(_bullet_list(suggested_skills))

    # Project Files Detected
    detected_files = [f for f, present in analysis.project_files.items() if present]
    if detected_files:
        sections.append("## Key Project Files\n")
        sections.append(_bullet_list(sorted(detected_files)))

    return "\n".join(sections)


def build_skill_kg_instructions(project_name: str) -> str:
    """Build the KG context-first workflow instructions for SKILL.md.

    These instructions are appended to the project-context SKILL.md so that
    any coding agent (Windsurf, Claude, OpenCode, Cursor) knows to query the
    Knowledge Graph before starting work.

    Args:
        project_name: Name of the project (used in tool call examples).

    Returns:
        Markdown string to append to SKILL.md.
    """
    return f"""
## Context-First Workflow (Knowledge Graph)

This project's context has been ingested into the Knowledge Graph.
**Before starting any coding task**, follow these steps:

1. **Get project overview** — call `get_project_context(project="{project_name}")`
2. **Search for relevant context** — call `search_business_context(query="<your task description>")`
3. **Review results** before writing or modifying code
4. **When unsure about patterns** — call `search_business_context(query="conventions for <topic>")`

> These tools are provided by the KG MCP server.
> If the tools are not available, read this SKILL.md for baseline context.
"""


def save_hybrid_kg_context(
    project_path: Path,
    analysis: ProjectAnalysis,
    installed_skills: list[str],
    suggested_skills: Optional[list[str]] = None,
) -> Path:
    """Generate and save hybrid kg-context.md with Graphify analysis.
    
    Args:
        project_path: Absolute path to the project root.
        analysis: ProjectAnalysis from the analyzer.
        installed_skills: Names of installed skills.
        suggested_skills: Names of suggested skills.
        
    Returns:
        Path to the saved kg-context.md file.
    """
    try:
        from agentic_cli.kg.graphify_integration import (
            generate_graphify_analysis, 
            format_graphify_insights
        )
        
        # Generate base context
        base_content = build_kg_context_document(
            project_path, analysis, installed_skills, suggested_skills
        )
        
        # Generate Graphify analysis
        console.print("[dim]Generating Graphify code structure analysis...[/dim]")
        graphify_data = generate_graphify_analysis(project_path)
        
        # Format Graphify insights
        graphify_insights = format_graphify_insights(graphify_data)
        
        # Combine content
        hybrid_content = base_content + "\n\n" + graphify_insights
        
        # Save hybrid code context (Graphify-enriched)
        skill_dir = project_path / ".skills" / "project-context"
        skill_dir.mkdir(parents=True, exist_ok=True)
        
        context_path = skill_dir / "kg-code-context.md"
        context_path.write_text(hybrid_content)
        
        console.print(f"[green]Code context saved with Graphify analysis[/green]")
        return context_path
        
    except ImportError:
        console.print("[yellow]Graphify not available, using base context only[/yellow]")
        return save_kg_context(project_path, analysis, installed_skills, suggested_skills)
    except Exception as e:
        console.print(f"[yellow]Graphify analysis failed, using base context: {e}[/yellow]")
        return save_kg_context(project_path, analysis, installed_skills, suggested_skills)


def save_kg_context(
    project_path: Path,
    analysis: ProjectAnalysis,
    installed_skills: list[str],
    suggested_skills: Optional[list[str]] = None,
) -> Path:
    """Generate and save kg-code-context.md to the project's .skills/ directory.

    Naming convention:
      - kg-code-context.md   → code structure/stack context (this file, with or without Graphify)
      - kg-<domain>-context.md → business/requirements context per domain (generated separately)

    Args:
        project_path: Absolute path to the project root.
        analysis: ProjectAnalysis from the analyzer/detector.
        installed_skills: Names of installed skills.
        suggested_skills: Names of suggested skills.

    Returns:
        Path to the saved kg-code-context.md file.
    """
    content = build_kg_context_document(
        project_path, analysis, installed_skills, suggested_skills
    )
    skill_dir = project_path / ".skills" / "project-context"
    skill_dir.mkdir(parents=True, exist_ok=True)

    context_path = skill_dir / "kg-code-context.md"
    context_path.write_text(content)
    return context_path


def save_kg_business_context(
    project_path: Path,
    domain_slug: str,
    content: str,
) -> Path:
    """Save business/requirements context as kg-<domain>-context.md.

    This file is the counterpart to kg-code-context.md — it contains
    Confluence OneViews, PDF requirements, and domain specs ingested
    separately and linked to code context in Neo4j.

    Args:
        project_path: Absolute path to the project root (or domain workspace).
        domain_slug: Domain identifier e.g. 'cwow-facility', 'cwow-patient'.
        content: Markdown content from Confluence/PDF ingestion.

    Returns:
        Path to the saved kg-<domain>-context.md file.
    """
    skill_dir = project_path / ".skills" / "project-context"
    skill_dir.mkdir(parents=True, exist_ok=True)

    context_path = skill_dir / f"kg-{domain_slug}-context.md"
    context_path.write_text(content)
    return context_path


def patch_skill_md_with_kg_instructions(project_path: Path) -> bool:
    """Append KG instructions to the project-context SKILL.md if not already present.

    Args:
        project_path: Absolute path to the project root.

    Returns:
        True if SKILL.md was updated, False if already patched or missing.
    """
    skill_md = project_path / ".skills" / "project-context" / "SKILL.md"
    if not skill_md.exists():
        return False

    existing = skill_md.read_text()
    marker = "## Context-First Workflow (Knowledge Graph)"
    if marker in existing:
        return False  # already patched

    instructions = build_skill_kg_instructions(project_path.name)
    skill_md.write_text(existing.rstrip() + "\n" + instructions)
    return True


def register_kg_data_source(
    project_path: Path,
    analysis: ProjectAnalysis,
) -> dict[str, Any]:
    """Register the project's context directory as a data source.

    Adds an entry to ``~/.agent-cli-agentic/config.json`` → ``data.sources[]``
    so that ``agent-cli kg ingest submit --source onboard-<project>`` works.

    The source is idempotent — re-onboarding overwrites the existing entry.

    Args:
        project_path: Absolute path to the project root.
        analysis: ProjectAnalysis (used for tags).

    Returns:
        The data-source dict that was written.
    """
    config_dir = Path.home() / ".agent-cli-agentic"
    config_file = config_dir / "config.json"

    # Load existing config
    config: dict[str, Any] = {}
    if config_file.exists():
        try:
            config = json.loads(config_file.read_text())
        except (json.JSONDecodeError, OSError):
            pass

    # Ensure data section
    if "data" not in config:
        config["data"] = {"globals": {"gcs": {}, "confluence": {}}, "sources": []}
    if "sources" not in config["data"]:
        config["data"]["sources"] = []

    project_name = project_path.name
    source_name = f"onboard-{project_name}"
    context_dir = str(project_path / ".skills" / "project-context")

    # Build tags from analysis
    tags = ["onboard", "project-context"]
    tags.extend(analysis.languages[:3])
    tags.extend(analysis.frameworks[:3])

    new_source = {
        "name": source_name,
        "type": "doc",
        "location": context_dir,
        "description": f"Auto-generated project context from agent-cli code onboard for {project_name}",
        "tags": [t.lower() for t in tags],
        "project": project_name,
        "kg_status": "registered",
        "created_at": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
    }

    # Idempotent: remove existing entry with same name
    config["data"]["sources"] = [
        s for s in config["data"]["sources"] if s.get("name") != source_name
    ]
    config["data"]["sources"].append(new_source)

    # Save
    config_dir.mkdir(parents=True, exist_ok=True)
    config_file.write_text(json.dumps(config, indent=2))

    return new_source


def ingest_context_to_lightrag(
    context_path: Path,
    project_name: str,
    lightrag_url: str = "http://localhost:8001",
    timeout: float = 30.0,
) -> dict[str, Any]:
    """Insert the kg-context.md document into LightRAG for semantic search.

    This is the *light mode* ingestion — text only, no entity extraction.

    Args:
        context_path: Path to kg-context.md.
        project_name: Project name (used in metadata).
        lightrag_url: Base URL of the LightRAG server.
        timeout: Request timeout in seconds.

    Returns:
        LightRAG insert result dict.

    Raises:
        FileNotFoundError: If context_path doesn't exist.
        ImportError: If httpx is not installed.
        Exception: On connection or insert errors.
    """
    if not context_path.exists():
        raise FileNotFoundError(f"Context file not found: {context_path}")

    from agentic_cli.kg.lightrag_client import LightRAGClient

    text = context_path.read_text()
    # Derive doc_type from filename: kg-code-context.md → code_context, kg-<domain>-context.md → business_context
    name = context_path.name
    if name == "kg-code-context.md":
        doc_type = "code_context"
    elif name.startswith("kg-") and name.endswith("-context.md"):
        doc_type = "business_context"
    else:
        doc_type = "project_context"
    metadata = {
        "source": "agent-cli-code-onboard",
        "project": project_name,
        "doc_type": doc_type,
        "filename": name,
        "filepath": str(context_path),
    }

    client = LightRAGClient(base_url=lightrag_url, timeout=timeout)
    try:
        return client.insert(text, metadata)
    finally:
        client.close()


def run_kg_context_pipeline(
    project_path: Path,
    analysis: ProjectAnalysis,
    installed_skills: list[str],
    suggested_skills: Optional[list[str]] = None,
    ingest: bool = True,
    lightrag_url: str = "http://localhost:8001",
    use_graphify: bool = False,
) -> dict[str, Any]:
    """Run the full KG context pipeline: build, save, register, ingest.

    This is the main entry point called from ``agent-cli code onboard --kg``.

    Args:
        project_path: Absolute path to the project root.
        analysis: ProjectAnalysis from the analyzer.
        installed_skills: Names of installed skills.
        suggested_skills: Names of suggested skills.
        ingest: If True, also ingest into LightRAG.
        lightrag_url: LightRAG server URL.
        use_graphify: If True, include Graphify code structure analysis.

    Returns:
        Result dict with keys: context_path, source, skill_patched,
        ingested, ingest_result, graphify_analysis.
    """
    result: dict[str, Any] = {
        "context_path": None,
        "source": None,
        "skill_patched": False,
        "ingested": False,
        "ingest_result": None,
        "graphify_analysis": None,
        "errors": [],
    }

    # 1. Build and save kg-context.md (with optional Graphify)
    if use_graphify:
        context_path = save_hybrid_kg_context(
            project_path, analysis, installed_skills, suggested_skills
        )
    else:
        context_path = save_kg_context(
            project_path, analysis, installed_skills, suggested_skills
        )
    result["context_path"] = str(context_path)

    # 2. Run Graphify analysis (if requested)
    if use_graphify:
        try:
            from agentic_cli.kg.graphify_integration import (
                generate_graphify_analysis, 
                validate_graphify_compatibility
            )
            
            # Validate compatibility
            validation = validate_graphify_compatibility(project_path)
            if validation["compatible"]:
                console.print("[dim]Running Graphify code structure analysis...[/dim]")
                graphify_data = generate_graphify_analysis(project_path)
                result["graphify_analysis"] = {
                    "status": "completed",
                    "data": graphify_data,
                    "validation": validation
                }
                console.print(f"[green]Graphify analysis complete: {len(graphify_data.get('nodes', []))} nodes, {len(graphify_data.get('edges', []))} relationships[/green]")
            else:
                result["errors"].append(f"Graphify validation failed: {validation['reason']}")
                console.print(f"[yellow]Graphify validation failed: {validation['reason']}[/yellow]")
                
        except ImportError:
            result["errors"].append("Graphify not installed. Install with: pip install graphifyy")
            console.print("[yellow]Graphify not installed. Install with: pip install graphifyy[/yellow]")
        except Exception as e:
            result["errors"].append(f"Graphify analysis failed: {e}")
            console.print(f"[yellow]Graphify analysis failed: {e}[/yellow]")

    # 3. Patch SKILL.md with KG instructions
    result["skill_patched"] = patch_skill_md_with_kg_instructions(project_path)

    # 4. Register as data source
    try:
        source = register_kg_data_source(project_path, analysis)
        result["source"] = source
    except Exception as e:
        result["errors"].append(f"Data source registration failed: {e}")

    # 5. Ingest into LightRAG (if requested and available)
    if ingest:
        try:
            ingest_result = ingest_context_to_lightrag(
                context_path,
                project_path.name,
                lightrag_url=lightrag_url,
            )
            result["ingested"] = True
            result["ingest_result"] = ingest_result
        except ImportError as e:
            result["errors"].append(f"LightRAG client not available: {e}")
        except Exception as e:
            result["errors"].append(f"LightRAG ingestion failed: {e}")

    return result
