"""KG Sync Layer — push tracker.db platform data to LightRAG.

Bridges the gap between CLI-local tracker.db and the Knowledge Graph
so that agents connected via KG MCP can query platform context:
  - Onboarded repositories (tech stacks, skills, frameworks)
  - Created agent projects (use-cases, tools)
  - Recent CLI activity (what happened, when)
  - Domains (once registered via `dva domain`)

Usage:
    dva kg sync              # sync all (repos + projects + activity)
    dva kg sync --repos      # just repos
    dva kg sync --projects   # just projects
    dva kg sync --activity   # just recent activity
"""

import json
import logging
from datetime import datetime, timezone
from typing import Any, Optional

from agentic_cli.tracker import (
    get_repos,
    get_projects,
    get_activity,
    get_activity_summary,
)

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Document Builders
# ---------------------------------------------------------------------------

def build_repos_document(repos: list[dict]) -> str:
    """Build a markdown document summarizing all onboarded repositories."""
    if not repos:
        return ""

    ts = datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")
    lines = [
        "# DVA Platform — Onboarded Repositories\n",
        f"> Auto-generated by `dva kg sync` on {ts}.\n",
        f"> {len(repos)} repositories tracked by the DVA Agentic Platform.\n",
        "## Repository Index\n",
    ]

    for repo in repos:
        name = repo.get("name", "unknown")
        path = repo.get("path", "")
        url = repo.get("repo_url") or ""
        languages = repo.get("languages", [])
        frameworks = repo.get("frameworks", [])
        build_tools = repo.get("build_tools", [])
        test_fws = repo.get("test_frameworks", [])
        databases = repo.get("databases", [])
        skills = repo.get("skills_installed", [])
        deps = repo.get("dependencies", 0)
        docker = repo.get("has_docker", False)
        onboarded = repo.get("onboarded_at", "")
        updated = repo.get("last_updated_at", "")

        # Normalize JSON fields that may still be strings
        for field in (languages, frameworks, build_tools, test_fws, databases, skills):
            if isinstance(field, str):
                try:
                    field = json.loads(field)
                except (json.JSONDecodeError, TypeError):
                    field = []

        lines.append(f"### {name}\n")
        if url:
            lines.append(f"- **Repository URL:** {url}")
        lines.append(f"- **Local Path:** `{path}`")
        lines.append(f"- **Languages:** {', '.join(languages) if languages else 'Unknown'}")
        lines.append(f"- **Frameworks:** {', '.join(frameworks) if frameworks else '—'}")
        if build_tools:
            lines.append(f"- **Build Tools:** {', '.join(build_tools)}")
        if test_fws:
            lines.append(f"- **Test Frameworks:** {', '.join(test_fws)}")
        if databases:
            lines.append(f"- **Databases:** {', '.join(databases)}")
        lines.append(f"- **Dependencies:** {deps}")
        lines.append(f"- **Docker:** {'Yes' if docker else 'No'}")
        if skills:
            lines.append(f"- **Installed Skills:** {', '.join(skills)}")
        lines.append(f"- **Onboarded:** {onboarded}")
        if updated and updated != onboarded:
            lines.append(f"- **Last Updated:** {updated}")
        lines.append("")

    return "\n".join(lines)


def build_projects_document(projects: list[dict]) -> str:
    """Build a markdown document summarizing all created agent projects."""
    if not projects:
        return ""

    ts = datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")
    lines = [
        "# DVA Platform — Agent Projects\n",
        f"> Auto-generated by `dva kg sync` on {ts}.\n",
        f"> {len(projects)} agent projects created via the DVA Agentic Platform.\n",
        "## Project Index\n",
    ]

    for proj in projects:
        name = proj.get("name", "unknown")
        path = proj.get("path", "")
        framework = proj.get("framework", "unknown")
        use_case = proj.get("use_case", "basic")
        tools = proj.get("tools", [])
        created = proj.get("created_at", "")

        if isinstance(tools, str):
            try:
                tools = json.loads(tools)
            except (json.JSONDecodeError, TypeError):
                tools = []

        lines.append(f"### {name}\n")
        lines.append(f"- **Path:** `{path}`")
        lines.append(f"- **Framework:** {framework}")
        lines.append(f"- **Use Case:** {use_case}")
        if tools:
            lines.append(f"- **Tools:** {', '.join(tools)}")
        lines.append(f"- **Created:** {created}")
        lines.append("")

    return "\n".join(lines)


def build_activity_document(
    activities: list[dict],
    summary: dict,
    since: Optional[str] = None,
) -> str:
    """Build a markdown document summarizing recent CLI activity."""
    if not activities:
        return ""

    ts = datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")
    period = f" (since {since})" if since else ""
    lines = [
        "# DVA Platform — Recent Activity\n",
        f"> Auto-generated by `dva kg sync` on {ts}.\n",
        f"> Showing {len(activities)} recent actions{period}.\n",
        "## Summary\n",
        f"- **Total Actions:** {summary.get('total_actions', 0)}",
        f"- **Success Rate:** {summary.get('success_rate', 'N/A')}",
        f"- **Last Activity:** {summary.get('last_activity', 'N/A')}",
    ]

    cmds = summary.get("commands", {})
    if cmds:
        lines.append(f"- **Command Breakdown:** " + ", ".join(
            f"{cmd} ({cnt})" for cmd, cnt in cmds.items()
        ))
    lines.append("")

    lines.append("## Recent Actions\n")
    for act in activities[:50]:
        ts_str = act.get("timestamp", "")[:19]
        cmd = act.get("command", "")
        sub = act.get("subcommand", "")
        status = act.get("status", "success")
        icon = "✓" if status == "success" else "✗"
        duration = act.get("duration_ms")
        dur_str = f" ({duration}ms)" if duration else ""

        label = f"{cmd} {sub}".strip()
        lines.append(f"- **{ts_str}** {icon} `{label}`{dur_str}")

        # Show key details
        details = act.get("details")
        if details:
            if isinstance(details, str):
                try:
                    details = json.loads(details)
                except (json.JSONDecodeError, TypeError):
                    details = {}
            if isinstance(details, dict):
                for k, v in list(details.items())[:3]:
                    lines.append(f"  - {k}: {v}")

    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Sync Engine
# ---------------------------------------------------------------------------

class KGSyncResult:
    """Result of a sync operation."""

    def __init__(self):
        self.repos_synced: int = 0
        self.projects_synced: int = 0
        self.activities_synced: int = 0
        self.total_chars: int = 0
        self.errors: list[str] = []

    @property
    def total_documents(self) -> int:
        return sum(1 for x in (self.repos_synced, self.projects_synced, self.activities_synced) if x > 0)


def sync_to_lightrag(
    sync_repos: bool = True,
    sync_projects: bool = True,
    sync_activity: bool = True,
    activity_limit: int = 50,
    activity_since: Optional[str] = None,
) -> KGSyncResult:
    """Push tracker.db platform data to LightRAG.

    Args:
        sync_repos: Sync onboarded repositories.
        sync_projects: Sync created agent projects.
        sync_activity: Sync recent CLI activity.
        activity_limit: Max activity records to include.
        activity_since: ISO timestamp — only include activity after this.

    Returns:
        KGSyncResult with counts and errors.
    """
    from agentic_cli.kg.config import KGConfig  # noqa: lazy
    from agentic_cli.kg.lightrag_client import LightRAGClient  # noqa: lazy

    result = KGSyncResult()
    config = KGConfig.load()
    client = LightRAGClient(base_url=config.lightrag_url, timeout=config.lightrag_timeout)

    # --- Repos ---
    if sync_repos:
        repos = get_repos()
        if repos:
            doc = build_repos_document(repos)
            if doc:
                try:
                    resp = client.insert(doc, metadata={
                        "source": "dva-platform-sync",
                        "type": "repos",
                        "count": len(repos),
                    })
                    result.repos_synced = len(repos)
                    result.total_chars += resp.get("characters", len(doc))
                except Exception as e:
                    result.errors.append(f"repos: {e}")

    # --- Projects ---
    if sync_projects:
        projects = get_projects()
        if projects:
            doc = build_projects_document(projects)
            if doc:
                try:
                    resp = client.insert(doc, metadata={
                        "source": "dva-platform-sync",
                        "type": "projects",
                        "count": len(projects),
                    })
                    result.projects_synced = len(projects)
                    result.total_chars += resp.get("characters", len(doc))
                except Exception as e:
                    result.errors.append(f"projects: {e}")

    # --- Activity ---
    if sync_activity:
        activities = get_activity(limit=activity_limit, since=activity_since)
        summary = get_activity_summary()
        if activities:
            doc = build_activity_document(activities, summary, since=activity_since)
            if doc:
                try:
                    resp = client.insert(doc, metadata={
                        "source": "dva-platform-sync",
                        "type": "activity",
                        "count": len(activities),
                    })
                    result.activities_synced = len(activities)
                    result.total_chars += resp.get("characters", len(doc))
                except Exception as e:
                    result.errors.append(f"activity: {e}")

    try:
        client.close()
    except Exception:
        pass

    return result
