"""Generate ADK tool classes for knowledge graph operations."""

from typing import List


def generate_tool(name: str, operations: List[str]) -> str:
    """
    Generate an ADK tool class for knowledge graph operations.
    
    Args:
        name: Tool name
        operations: List of operations to include (search, query, traverse)
    
    Returns:
        Python code for the tool class
    """
    class_name = "".join(word.capitalize() for word in name.split("_")) + "Tool"
    
    # Base imports
    imports = [
        "from typing import Any, Dict, List, Optional",
        "from agentic_cli.kg.config import KGConfig",
        "from agentic_cli.kg.neo4j_client import Neo4jClient",
    ]
    
    # Add operation-specific imports
    if "search" in operations:
        imports.append("from agentic_cli.kg.search import search_graph")
    if "query" in operations:
        imports.append("from agentic_cli.kg.query import execute_query")
    
    # Generate methods
    methods = []
    
    if "search" in operations:
        methods.append("""
    def search(
        self,
        text: str,
        semantic: bool = True,
        limit: int = 10,
    ) -> List[Dict[str, Any]]:
        \"\"\"
        Search the knowledge graph.
        
        Args:
            text: Search text
            semantic: Use semantic search (embeddings) or exact match
            limit: Maximum number of results
        
        Returns:
            List of search results
        \"\"\"
        return search_graph(text, semantic=semantic, limit=limit)
""")
    
    if "query" in operations:
        methods.append("""
    def query(
        self,
        query_text: str,
        format: str = "natural",
        limit: int = 10,
    ) -> List[str]:
        \"\"\"
        Query the knowledge graph.
        
        Args:
            query_text: Query string
            format: Query format ('natural' or 'cypher')
            limit: Maximum number of results
        
        Returns:
            List of result strings
        \"\"\"
        return execute_query(query_text, format=format, limit=limit)
""")
    
    if "traverse" in operations:
        methods.append("""
    def traverse(
        self,
        start_node_id: str,
        relationship_type: Optional[str] = None,
        depth: int = 2,
    ) -> Dict[str, Any]:
        \"\"\"
        Traverse the graph from a starting node.
        
        Args:
            start_node_id: ID of the starting node
            relationship_type: Filter by relationship type (optional)
            depth: Maximum traversal depth
        
        Returns:
            Dictionary with nodes and relationships
        \"\"\"
        config = KGConfig.load()
        
        rel_filter = f":{relationship_type}" if relationship_type else ""
        
        query = f\"\"\"
        MATCH path = (start)-[{rel_filter}*1..{depth}]-(connected)
        WHERE start.id = $start_id
        RETURN path
        LIMIT 100
        \"\"\"
        
        with Neo4jClient(config) as client:
            results = client.execute_cypher(query, {"start_id": start_node_id})
        
        return {
            "start_node": start_node_id,
            "paths": results,
            "count": len(results),
        }
""")
    
    # Generate the complete class
    code = f'''"""
Auto-generated ADK tool for knowledge graph operations.

Generated by: agent-cli kg tool generate
"""

{chr(10).join(imports)}


class {class_name}:
    """Tool for knowledge graph operations."""
    
    def __init__(self):
        """Initialize the knowledge graph tool."""
        self.config = KGConfig.load()
        
        if not self.config.is_neo4j_configured():
            raise ValueError(
                "Neo4j is not configured. Run '{CLI_NAME} kg init' first."
            )
{"".join(methods)}
    def get_stats(self) -> Dict[str, Any]:
        """
        Get knowledge graph statistics.
        
        Returns:
            Dictionary with statistics
        """
        with Neo4jClient(self.config) as client:
            return client.get_stats()


# Example usage
if __name__ == "__main__":
    tool = {class_name}()
    
    # Get stats
    stats = tool.get_stats()
    print(f"Nodes: {{stats['nodes']}}")
    print(f"Relationships: {{stats['relationships']}}")
'''
    
    return code


def generate_tool_template() -> str:
    """
    Generate a template for custom knowledge graph tools.
    
    Returns:
        Python code template
    """
    return '''"""
Custom knowledge graph tool template.

Extend this class to create custom knowledge graph operations.
"""

from typing import Any, Dict, List, Optional

from agentic_cli.kg.config import KGConfig
from agentic_cli.kg.neo4j_client import Neo4jClient
from agentic_cli.config import CLI_NAME


class CustomKGTool:
    """Custom knowledge graph tool."""
    
    def __init__(self):
        """Initialize the tool."""
        self.config = KGConfig.load()
        
        if not self.config.is_neo4j_configured():
            raise ValueError(
                "Neo4j is not configured. Run '{CLI_NAME} kg init' first."
            )
    
    def custom_operation(self, *args, **kwargs) -> Any:
        """
        Implement your custom operation here.
        
        Example:
            with Neo4jClient(self.config) as client:
                results = client.execute_cypher("YOUR CYPHER QUERY")
                return results
        """
        raise NotImplementedError("Implement your custom operation")
'''
