"""Template identity for generated domain meta-repos.

``scaffold_domain_meta_repo`` renders a meta-repo from the built-in template.
Historically that was a one-way copy: nothing recorded *which* template produced
the repo or what the generated files looked like. Once a team started evolving
its meta-repo (new skills, tightened ``GOVERNANCE.md``, edited ``AGENTS.md``),
the platform could no longer tell a template change from a local edit — so
template improvements could never be retrofitted, and local improvements could
never be promoted back upstream.

This module writes ``.platform/template.json``: the template's fingerprint at
generation time — its version, a sha256 per generated file, and the inputs
needed to re-render it deterministically. :mod:`template_drift` diffs a live
meta-repo against a fresh render using that as the baseline.

Scope is deliberately the *template surface* — the governance/agent content the
template owns. Everything else is excluded, and each exclusion is a decision:

- **Per-domain data** (``domain.yaml``, ``repos.yaml``) — owned by
  ``keel domain create`` / ``link-repo``, not the template. ``domain.yaml`` also
  carries a ``created_at`` stamp, so it could never compare equal.
- **Per-domain renders** (``.agents/skills/personas/``) — owned by
  ``keel domain regen-personas``; AI-enriched and domain-specific by design.
- **Installed skills** (``.skills/``) — injected from the superpowers baseline
  and the skills registry, not rendered by the template. Flagging all of them as
  local content would be wrong: most are upstream skills, not domain-authored.
  Telling the two apart needs ``skills-manifest.json`` (which records
  ``source: superpowers`` vs domain-authored), so skill promotion is handled by
  the skills path rather than this file classifier.
- **Editor mirrors** (``.devin/skills/``, ``.windsurf/workflows/``,
  ``.cursor/rules/``) — derived placements of the *same* skills, rewritten by
  ``keel domain reinstall-skills``. Tracking them would report every skill two
  or three times.
"""
from __future__ import annotations

import hashlib
import json
import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterator, Optional

logger = logging.getLogger(__name__)

# Bump when the built-in template's *content* changes. Recorded in every
# generated meta-repo so `keel domain template status` can report how far a
# domain has fallen behind, even before hashing anything.
TEMPLATE_VERSION = "1.0.0"

MANIFEST_REL = ".platform/template.json"

# Roots the template owns. Everything else in a meta-repo (repos/ submodules,
# plans/, generated graphs, knowledge bundles) is out of scope.
TRACKED_ROOTS: tuple[str, ...] = (
    "AGENTS.md",
    "README.md",
    "Makefile",
    ".gitignore",
    ".platform",
    ".agents",
    "docs",
    ".githooks",
)

# Never walked into: VCS internals, submodule checkouts, local scratch, build
# and tool caches, generated graph/knowledge artifacts.
PRUNE_DIRS = frozenset({
    ".git", "repos", "plans", "node_modules", "__pycache__", ".graph",
    "knowledge", "knowledge-export", ".venv", "venv", ".mypy_cache",
    ".pytest_cache", ".ruff_cache", "dist", "build", ".idea", ".vscode",
})

# Per-domain data or derived artifacts, not template content (see docstring).
# `skills-manifest.json` is regenerated by `make load-skills` and gitignored.
EXCLUDED_FILES = frozenset({
    MANIFEST_REL,
    ".platform/config/domain.yaml",
    ".platform/config/repos.yaml",
    ".platform/skills-manifest.json",
})

EXCLUDED_PREFIXES: tuple[str, ...] = (".agents/skills/personas/",)

_IGNORED_NAMES = frozenset({".DS_Store", "Thumbs.db"})
_IGNORED_SUFFIXES = (".pyc", ".pyo", ".orig", ".rej", ".new")


def is_tracked(rel: str) -> bool:
    """True if ``rel`` (a POSIX-style relative path) is template surface."""
    if rel in EXCLUDED_FILES or rel.startswith(EXCLUDED_PREFIXES):
        return False
    name = rel.rsplit("/", 1)[-1]
    if name in _IGNORED_NAMES or rel.endswith(_IGNORED_SUFFIXES):
        return False
    return True


def _walk_dir(root: Path, directory: Path) -> Iterator[str]:
    """Yield tracked relative paths under ``directory``, pruning noise dirs."""
    stack = [directory]
    while stack:
        current = stack.pop()
        try:
            entries = sorted(current.iterdir())
        except OSError:  # unreadable dir — nothing to compare
            continue
        for entry in entries:
            if entry.is_symlink():
                # Submodule/worktree links are not template content.
                continue
            if entry.is_dir():
                if entry.name not in PRUNE_DIRS:
                    stack.append(entry)
            elif entry.is_file():
                rel = entry.relative_to(root).as_posix()
                if is_tracked(rel):
                    yield rel


def iter_surface(root: Path) -> Iterator[str]:
    """Yield every tracked relative path in a meta-repo, sorted per root."""
    for entry_name in TRACKED_ROOTS:
        entry = root / entry_name
        if entry.is_symlink():
            continue
        if entry.is_file():
            if is_tracked(entry_name):
                yield entry_name
        elif entry.is_dir():
            yield from _walk_dir(root, entry)


def sha256_file(path: Path) -> str:
    """sha256 of a file's raw bytes (hex)."""
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def hash_surface(root: Path) -> dict[str, str]:
    """Map every tracked relative path in ``root`` to its sha256."""
    out: dict[str, str] = {}
    for rel in iter_surface(root):
        try:
            out[rel] = sha256_file(root / rel)
        except OSError:  # vanished mid-walk
            continue
    return dict(sorted(out.items()))


def build_manifest(
    meta_repo_path: Path,
    domain: str,
    product: str,
    description: str = "",
    owner: str = "",
) -> dict:
    """Build the manifest dict for a freshly generated meta-repo.

    ``render_inputs`` captures exactly what a deterministic re-render needs, so
    drift detection never has to guess the values baked into the docs.
    """
    return {
        "template_version": TEMPLATE_VERSION,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "render_inputs": {
            "domain": domain,
            "product": product,
            "description": description or "",
            "owner": owner or "",
        },
        "files": hash_surface(meta_repo_path),
    }


def write_manifest(
    meta_repo_path: Path,
    domain: str,
    product: str,
    description: str = "",
    owner: str = "",
) -> Path:
    """Write ``.platform/template.json`` into a generated meta-repo."""
    manifest = build_manifest(meta_repo_path, domain, product, description, owner)
    target = meta_repo_path / MANIFEST_REL
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    logger.debug(
        "Wrote template manifest (%s files, v%s) to %s",
        len(manifest["files"]), TEMPLATE_VERSION, target,
    )
    return target


def read_manifest(meta_repo_path: Path) -> Optional[dict]:
    """Read a meta-repo's template manifest, or None when absent/unreadable.

    Meta-repos generated before manifests existed simply have no baseline;
    callers degrade to a baseline-free comparison rather than failing.
    """
    path = Path(meta_repo_path) / MANIFEST_REL
    if not path.is_file():
        return None
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError) as e:
        logger.warning("Unreadable template manifest at %s: %s", path, e)
        return None
    return data if isinstance(data, dict) else None


def recorded_version(meta_repo_path: Path) -> Optional[str]:
    """The template version recorded in a meta-repo, if any."""
    manifest = read_manifest(meta_repo_path)
    if not manifest:
        return None
    version = manifest.get("template_version")
    return str(version) if version else None
