"""``{CLI_NAME} domain template`` — track a meta-repo against its template.

Generated meta-repos evolve: teams add skills, tighten ``docs/GOVERNANCE.md``,
edit ``AGENTS.md``. The template evolves too. This command group reports how the
two have diverged, so template improvements can be retrofitted and local
improvements can be promoted back upstream instead of being stranded in one
domain.

``status`` is read-only; ``upgrade`` pulls template updates down into a
meta-repo, and ``promote`` pushes a domain's local improvements up into the
shared template overlay.
"""
from __future__ import annotations

import json as _json
from pathlib import Path
from typing import Optional

import typer
from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from typing_extensions import Annotated

from agentic_cli.config import CLI_NAME
from agentic_cli.meta_repo import template_drift as drift
from agentic_cli.meta_repo import template_overlay as ov
from agentic_cli.meta_repo import template_promote as prom
from agentic_cli.meta_repo import template_upgrade as upg

template_app = typer.Typer(
    help="Template lifecycle — compare, upgrade, and promote meta-repo templates",
    rich_markup_mode=None,
)
console = Console()

# Status → (display colour, one-line meaning shown in the legend).
_STATUS_STYLE: dict[str, tuple[str, str]] = {
    drift.BOTH_MODIFIED: ("red", "edited locally AND updated in the template — needs review"),
    drift.NO_BASELINE: ("yellow", "differs from the template, no generation baseline recorded"),
    drift.TEMPLATE_UPDATED: ("cyan", "template has a newer version — safe to fast-forward"),
    drift.LOCALLY_MODIFIED: ("magenta", "edited locally — candidate to promote upstream"),
    drift.LOCAL_ONLY: ("green", "added locally — candidate to promote upstream"),
    drift.DELETED: ("yellow", "generated by the template but missing locally"),
    drift.TEMPLATE_REMOVED: ("dim", "the template no longer generates this file"),
    drift.UNCHANGED: ("dim", "matches the current template"),
}


def _style(status: str) -> str:
    return _STATUS_STYLE.get(status, ("white", ""))[0]


def _resolve_report(domain_name: str, meta: Optional[str]) -> drift.DriftReport:
    """Build the drift report, from an explicit path or by domain conventions."""
    try:
        if meta:
            path = Path(meta).expanduser().resolve()
            return drift.classify(path, domain=domain_name)
        return drift.classify_domain(domain_name)
    except FileNotFoundError as e:
        console.print(f"[red]✗[/red] {e}")
        raise typer.Exit(1)


@template_app.command("status")
def status(
    domain_name: Annotated[str, typer.Argument(help="Domain name (slug, e.g. cwow-facility)")],
    meta: Annotated[str, typer.Option("--meta", help="Path to the meta-repo (defaults to the workspace location)")] = None,
    show: Annotated[str, typer.Option("--show", help="Which files to list: drifted, all, or a status name (e.g. local-only)")] = "drifted",
    as_json: Annotated[bool, typer.Option("--json", help="Emit the raw report as JSON")] = False,
) -> None:
    """Report how a domain meta-repo has diverged from the current template.

    Read-only — nothing in the meta-repo is modified. Compares each tracked file
    across three points: its hash when generated (``.platform/template.json``),
    its hash in a fresh render of today's template, and its hash on disk.
    """
    report = _resolve_report(domain_name, meta)
    _record(report)

    if as_json:
        console.print_json(_json.dumps(report.to_dict()))
        return

    # ── Header: where we are and what baseline we have ──
    version = report.recorded_version or "unrecorded"
    lines = [
        f"Meta-repo:        {report.meta_repo}",
        f"Template version: {version}  (current: {report.current_version})",
        f"Tracked files:    {len(report.entries)}",
    ]
    if not report.has_baseline:
        lines.append(
            "\n[yellow]No .platform/template.json baseline.[/yellow] This meta-repo predates\n"
            "template tracking, so local edits can't be told apart from template\n"
            "updates — differing files are reported as 'no-baseline'."
        )
    elif report.version_behind:
        lines.append(
            f"\n[cyan]Generated from template v{version};[/cyan] the current template is "
            f"v{report.current_version}."
        )

    border = "green" if not report.drifted else (
        "red" if report.conflicted else "yellow")
    console.print(Panel("\n".join(lines),
                        title=f"Template status — {report.domain}",
                        border_style=border))

    if not report.entries:
        console.print("[yellow]No tracked template files found.[/yellow]")
        return

    # ── Summary counts ──
    summary = Table(show_header=True, header_style="bold")
    summary.add_column("Status")
    summary.add_column("Files", justify="right")
    summary.add_column("Meaning")
    for st, n in report.counts.items():
        colour, meaning = _STATUS_STYLE.get(st, ("white", ""))
        summary.add_row(f"[{colour}]{st}[/{colour}]", str(n), meaning)
    console.print(summary)

    # ── File listing ──
    selector = (show or "drifted").strip().lower()
    if selector == "all":
        listed = report.entries
    elif selector == "drifted":
        listed = [e for e in report.entries if e.status != drift.UNCHANGED]
    else:
        listed = report.of_status(selector)
        if not listed:
            known = ", ".join(drift.STATUS_ORDER)
            console.print(f"\n[dim]No files with status '{selector}'. Known statuses: {known}[/dim]")
            return

    if listed:
        table = Table(show_header=True, header_style="bold",
                      title=f"Files ({selector})", title_justify="left")
        table.add_column("Status", no_wrap=True)
        table.add_column("Path")
        for e in listed:
            table.add_row(f"[{_style(e.status)}]{e.status}[/{_style(e.status)}]", e.path)
        console.print(table)

    # ── What to do next ──
    if not report.drifted:
        console.print("\n[green]✓[/green] In sync with the current template.")
        return

    hints: list[str] = []
    if report.upgradable:
        hints.append(
            f"{len(report.upgradable)} file(s) can take template updates cleanly "
            f"(no local edits to preserve).")
    if report.promotable:
        hints.append(
            f"{len(report.promotable)} file(s) hold local content the template "
            f"doesn't have — promotion candidates.")
    if report.conflicted:
        hints.append(
            f"{len(report.conflicted)} file(s) changed on both sides and need a "
            f"lead to reconcile them.")
    hints.append(
        f"Inspect a group with: {CLI_NAME} domain template status {report.domain} "
        f"--show local-only")
    console.print(Panel("\n".join(f"• {h}" for h in hints),
                        title="Next", border_style="cyan"))


_ACTION_STYLE = {
    upg.UPDATED: "cyan",
    upg.RESTORED: "cyan",
    upg.CONFLICT: "red",
    upg.PRUNED: "yellow",
    upg.SKIPPED: "dim",
}


@template_app.command("upgrade")
def upgrade(
    domain_name: Annotated[str, typer.Argument(help="Domain name (slug, e.g. cwow-facility)")],
    meta: Annotated[str, typer.Option("--meta", help="Path to the meta-repo (defaults to the workspace location)")] = None,
    apply_changes: Annotated[bool, typer.Option("--apply", help="Actually write changes (default is a dry run)")] = False,
    yes: Annotated[bool, typer.Option("--yes", "-y", help="Skip the confirmation prompt when applying")] = False,
    prune: Annotated[bool, typer.Option("--prune", help="Also delete files the template no longer generates")] = False,
    force: Annotated[bool, typer.Option("--force", help="Overwrite files that have uncommitted git changes")] = False,
    no_conflict_files: Annotated[bool, typer.Option("--no-conflict-files", help="Don't write <file>.new sidecars for conflicts")] = False,
    as_json: Annotated[bool, typer.Option("--json", help="Emit the raw result as JSON")] = False,
) -> None:
    """Apply safe template updates to a domain meta-repo.

    Dry run by default — pass ``--apply`` to write. Only files untouched since
    generation are fast-forwarded; local edits and domain-authored files are
    preserved, and files that changed on both sides are left alone with the
    template's version written beside them as ``<file>.new``.
    """
    dry_run = not apply_changes

    # Preview first so a confirmation prompt can state exactly what will change.
    try:
        if meta:
            path = Path(meta).expanduser().resolve()
            preview = upg.upgrade(path, domain=domain_name, dry_run=True,
                                  prune=prune, force=force,
                                  write_conflicts=not no_conflict_files)
        else:
            preview = upg.upgrade_domain(domain_name, dry_run=True, prune=prune,
                                         force=force,
                                         write_conflicts=not no_conflict_files)
    except FileNotFoundError as e:
        console.print(f"[red]✗[/red] {e}")
        raise typer.Exit(1)

    _print_upgrade(preview, as_json=as_json and dry_run)
    if as_json and dry_run:
        return

    if dry_run:
        if preview.changed or preview.conflicts:
            console.print(Panel(
                f"Dry run — nothing was written.\n"
                f"Apply with: {CLI_NAME} domain template upgrade {preview.domain} --apply",
                title="Next", border_style="cyan"))
        return

    if not preview.changed and not preview.conflicts:
        console.print("[green]✓[/green] Already up to date — nothing to apply.")
        return

    if not yes:
        summary = ", ".join(f"{n} {a}" for a, n in preview.counts.items()
                            if a in (upg.UPDATED, upg.RESTORED, upg.PRUNED)) or "no writes"
        console.print(f"\n[bold]About to modify {preview.meta_repo}[/bold] ({summary}).")
        if not typer.confirm("Proceed?"):
            console.print("[yellow]Aborted.[/yellow]")
            raise typer.Exit(1)

    result = upg.upgrade(preview.meta_repo, domain=preview.domain, dry_run=False,
                         prune=prune, force=force,
                         write_conflicts=not no_conflict_files)
    _print_upgrade(result, as_json=as_json)
    if as_json:
        return

    tail = [f"Template version: {result.from_version or 'unrecorded'} → {result.to_version}"]
    if result.conflicts:
        tail.append(
            f"{len(result.conflicts)} conflict(s) need a manual merge — review the "
            f".new files, then commit.")
    tail.append(f"Review the diff: git -C {result.meta_repo} diff")
    console.print(Panel("\n".join(f"• {t}" for t in tail),
                        title="Applied", border_style="green"))


def _print_upgrade(result: "upg.UpgradeReport", as_json: bool = False) -> None:
    """Render an upgrade report (or its JSON)."""
    if as_json:
        console.print_json(_json.dumps(result.to_dict()))
        return

    header = [
        f"Meta-repo:        {result.meta_repo}",
        f"Template version: {result.from_version or 'unrecorded'} "
        f"(current: {result.to_version})",
        f"Files to change:  {result.changed}",
    ]
    for warning in result.blocked:
        header.append(f"\n[yellow]⚠ {warning}[/yellow]")
    console.print(Panel("\n".join(header),
                        title=f"{'Dry run' if result.dry_run else 'Upgrade'} — {result.domain}",
                        border_style="cyan" if result.dry_run else "green"))

    actionable = [a for a in result.actions if a.action != upg.SKIPPED]
    skipped = result.of_action(upg.SKIPPED)

    if actionable:
        table = Table(show_header=True, header_style="bold")
        table.add_column("Action", no_wrap=True)
        table.add_column("Path")
        table.add_column("Detail")
        for a in actionable:
            style = _ACTION_STYLE.get(a.action, "white")
            detail = a.detail + (f"  →  {a.sidecar}" if a.sidecar else "")
            table.add_row(f"[{style}]{a.action}[/{style}]", a.path, detail)
        console.print(table)
    else:
        console.print("[green]✓[/green] No template updates to apply.")

    if skipped:
        table = Table(show_header=True, header_style="bold", title="Preserved / skipped",
                      title_justify="left")
        table.add_column("Status", no_wrap=True)
        table.add_column("Path")
        table.add_column("Reason")
        for a in skipped:
            table.add_row(f"[dim]{a.status}[/dim]", a.path, a.detail)
        console.print(table)


@template_app.command("promote")
def promote(
    domain_name: Annotated[str, typer.Argument(help="Domain name (slug, e.g. cwow-facility)")],
    file: Annotated[list[str], typer.Option("--file", "-f", help="Repo-relative file to promote (repeatable)")] = None,
    meta: Annotated[str, typer.Option("--meta", help="Path to the meta-repo (defaults to the workspace location)")] = None,
    apply_changes: Annotated[bool, typer.Option("--apply", help="Actually write into the template overlay (default is a dry run)")] = False,
    push: Annotated[bool, typer.Option("--push", help="Push the promotion branch to origin")] = False,
    no_commit: Annotated[bool, typer.Option("--no-commit", help="Write overlay files without creating a branch/commit")] = False,
    allow_unreviewed: Annotated[bool, typer.Option("--allow-unreviewed", help="Proceed even when residual domain-specific content is detected")] = False,
    show: Annotated[bool, typer.Option("--show", help="Print the tokenized template body for review")] = False,
    as_json: Annotated[bool, typer.Option("--json", help="Emit the raw result as JSON")] = False,
) -> None:
    """Promote a domain's local template improvements into the shared template.

    Without ``--file``, lists what this domain could contribute. Promotion
    re-tokenizes the file (``cwow-apoc`` → ``{{domain}}``) and writes it to the
    template overlay, from where every other domain's next ``template upgrade``
    picks it up. Dry run by default.
    """
    try:
        if meta:
            meta_path = Path(meta).expanduser().resolve()
        else:
            from agentic_cli.meta_repo.detector import detect_domain_meta_repo

            found = detect_domain_meta_repo(domain_name)
            if found is None:
                console.print(
                    f"[red]✗[/red] No meta-repo found for domain '{domain_name}'.")
                raise typer.Exit(1)
            meta_path = found
        entries, inputs = prom.promotable(meta_path, domain=domain_name)
    except FileNotFoundError as e:
        console.print(f"[red]✗[/red] {e}")
        raise typer.Exit(1)

    # No file given → show the menu of what could be contributed.
    if not file:
        _print_promotable(meta_path, entries, inputs, domain_name, as_json=as_json)
        return

    try:
        result = prom.promote(
            meta_path, list(file), domain=domain_name,
            dry_run=not apply_changes, commit=not no_commit, push=push,
            allow_unreviewed=allow_unreviewed,
        )
    except ov.PromotionError as e:
        console.print(Panel(str(e), title="Blocked", border_style="red"))
        raise typer.Exit(1)

    if as_json:
        console.print_json(_json.dumps(result.to_dict()))
        return

    for plan in result.plans:
        lines = [
            f"File:     {plan.path}  ({plan.status})",
            f"Template: {plan.overlay_path}"
            + ("  [yellow](replaces an existing overlay file)[/yellow]"
               if plan.replaces_existing else ""),
        ]
        if plan.substitutions:
            subs = ", ".join(f"{s.count}× {s.value} → {{{{{s.placeholder}}}}}"
                             for s in plan.substitutions)
            lines.append(f"Tokenized: {subs}")
        else:
            lines.append("[yellow]Tokenized: nothing — no render inputs appear "
                         "in this file[/yellow]")
        if plan.skipped_values:
            lines.append(f"[yellow]Too short to tokenize safely: "
                         f"{', '.join(plan.skipped_values)}[/yellow]")
        for r in plan.residuals:
            lines.append(f"[yellow]⚠ {r.count}× {r.kind}: {r.sample}[/yellow]")
        console.print(Panel("\n".join(lines),
                            title=f"{'Would promote' if result.dry_run else 'Promoted'} — {plan.path}",
                            border_style="cyan" if result.dry_run else "green"))
        if show:
            console.print(Panel(plan.content[:4000],
                                title=f"Tokenized template — {plan.path}",
                                border_style="dim"))

    if result.dry_run:
        console.print(Panel(
            f"Dry run — the template overlay was not modified.\n"
            f"Apply with: {CLI_NAME} domain template promote {domain_name} "
            f"{' '.join(f'-f {f}' for f in file)} --apply",
            title="Next", border_style="cyan"))
        return

    tail = [f"Overlay: {result.overlay_root}"]
    if result.branch:
        tail.append(f"Branch:  {result.branch}"
                    + (f" @ {result.commit}" if result.commit else ""))
    if result.push_hint and not result.pushed:
        tail.append(f"Publish: {result.push_hint}")
    tail.append("Other domains pick this up on their next "
                f"'{CLI_NAME} domain template upgrade'.")
    console.print(Panel("\n".join(f"• {t}" for t in tail),
                        title="Applied", border_style="green"))


def _print_promotable(meta_path: Path, entries, inputs: dict, domain_name: str,
                      as_json: bool = False) -> None:
    """Show what a domain could contribute upstream."""
    if as_json:
        console.print_json(_json.dumps({
            "domain": inputs.get("domain", domain_name),
            "meta_repo": str(meta_path),
            "overlay_root": str(ov.overlay_root()),
            "promotable": [e.to_dict() for e in entries],
            "overlay_files": ov.list_overlay(),
        }))
        return

    console.print(Panel(
        f"Meta-repo: {meta_path}\n"
        f"Overlay:   {ov.overlay_root()}\n"
        f"Promotable: [bold]{len(entries)}[/bold] file(s)",
        title=f"Template promote — {inputs.get('domain', domain_name)}",
        border_style="green" if entries else "yellow"))

    if not entries:
        console.print(
            "[yellow]Nothing to promote.[/yellow] This domain has no locally "
            "modified or locally added template files.")
        return

    table = Table(show_header=True, header_style="bold")
    table.add_column("File")
    table.add_column("Status")
    table.add_column("Meaning")
    for e in entries:
        table.add_row(e.path, f"[{_style(e.status)}]{e.status}[/{_style(e.status)}]",
                      e.detail)
    console.print(table)
    console.print(Panel(
        f"{CLI_NAME} domain template promote {domain_name} -f {entries[0].path}\n"
        f"[dim]Dry run by default; add --show to review the tokenized body, "
        f"--apply to write.[/dim]",
        title="Promote", border_style="cyan"))


@template_app.command("overlay")
def overlay_list(
    as_json: Annotated[bool, typer.Option("--json", help="Emit the file list as JSON")] = False,
) -> None:
    """List the files the template overlay currently provides.

    These are promoted improvements that now ship to every new meta-repo and are
    offered to existing ones by ``template upgrade``.
    """
    root = ov.overlay_root()
    files = ov.list_overlay(root)
    if as_json:
        console.print_json(_json.dumps({"overlay_root": str(root), "files": files}))
        return

    console.print(Panel(
        f"Overlay root: {root}\n"
        f"Files:        [bold]{len(files)}[/bold]"
        + (f"\n[dim]Override with ${ov.OVERLAY_ENV}[/dim]" if not files else ""),
        title="Template overlay",
        border_style="green" if files else "dim"))
    if not files:
        console.print(
            "[dim]Empty — the template is entirely built-in defaults. Promote a "
            f"file with '{CLI_NAME} domain template promote <domain> -f <file>'.[/dim]")
        return
    for f in files:
        console.print(f"  • {f}")


def _record(report: drift.DriftReport) -> None:
    """Log the check to the central activity trail (never fatal)."""
    try:
        from agentic_cli.tracker import record_activity

        record_activity(
            command="domain", subcommand="template-status",
            entity_type="domain", entity_id=report.domain,
            args={"domain": report.domain},
            details={"drifted": report.drifted,
                     "template_version": report.recorded_version,
                     "current_version": report.current_version,
                     "counts": report.counts},
        )
    except Exception:  # noqa: BLE001 - auditing must never break the command
        pass
