"""Could a new joiner get their week-one questions answered from this domain?

The load-bearing rubric dimension, and the only one needing a model. It was left
reporting ``SKIPPED`` until the deterministic seven were trustworthy; this is it.

Three choices shape the design:

**The questions are deterministic.** They come from a fixed bank templated with
the domain's own product, repos and slug — not generated by a model. A generated
question set moves between runs, so a score built on it would drift for reasons
that have nothing to do with the context, and nobody could tell an improved
domain from a differently-worded exam. The model's job here is narrow: judge.

**The context under test is the finalized instruction set**, not a retrieval.
We are asking *"does this domain's context contain the answers?"* — a question
about coverage. Whether retrieval surfaces them is a different question with its
own metrics (ContextPrecision, ContextRecall), and conflating the two produces a
number that cannot be acted on: you would not know whether to write more context
or fix the retriever.

**An unparseable verdict is unknown, not zero.** If the judge returns something
we cannot read, this returns ``None`` and the dimension reports SKIPPED. A model
having a bad day must never look like an unready domain.
"""
from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from typing import Any, Optional

#: Verdicts the judge may return, and what each is worth.
ANSWERED = "answered"
PARTIAL = "partial"
MISSING = "missing"
_WEIGHTS = {ANSWERED: 1.0, PARTIAL: 0.5, MISSING: 0.0}

#: How many repos to template questions for. Every linked repo would make the
#: exam grow with the domain, so a domain gets *harder* to score well simply by
#: having more services — which is not what the dimension is measuring.
MAX_REPO_QUESTIONS = 3


@dataclass(frozen=True)
class Question:
    """One week-one question, and the rubric area it probes."""

    key: str
    area: str
    text: str


@dataclass
class Verdict:
    question: Question
    verdict: str
    why: str = ""

    @property
    def weight(self) -> float:
        return _WEIGHTS.get(self.verdict, 0.0)


@dataclass
class Report:
    """What the judge made of the domain's context."""

    verdicts: list[Verdict] = field(default_factory=list)
    model: str = ""

    @property
    def score(self) -> float:
        if not self.verdicts:
            return 0.0
        return 100.0 * sum(v.weight for v in self.verdicts) / len(self.verdicts)

    @property
    def answered(self) -> int:
        return sum(1 for v in self.verdicts if v.verdict == ANSWERED)

    @property
    def gaps(self) -> list[Verdict]:
        return [v for v in self.verdicts if v.verdict == MISSING]

    def to_dict(self) -> dict:
        return {
            "score": round(self.score, 1),
            "model": self.model,
            "answered": self.answered,
            "total": len(self.verdicts),
            "verdicts": [
                {"key": v.question.key, "area": v.question.area,
                 "question": v.question.text, "verdict": v.verdict, "why": v.why}
                for v in self.verdicts
            ],
        }


# The bank. ``{product}``, ``{domain}`` and ``{repo}`` are filled from the
# domain's own registration, so the exam speaks the team's vocabulary without a
# model inventing any of it.
_BANK: tuple[tuple[str, str, str], ...] = (
    ("purpose", "orientation", "What does the {domain} domain do, and what is it responsible for?"),
    ("entities", "orientation", "What are the core entities in {domain}, and what does each mean?"),
    ("prereqs", "runnable", "What must I install or have access to before I can build {product}?"),
    ("first-build", "runnable", "How do I get a clean checkout building and running for the first time?"),
    ("tests", "runnable", "How do I run the tests, and what has to pass before I open a pull request?"),
    ("ownership", "ownership", "Who owns each part of this domain, and where is that recorded?"),
    ("help", "ownership", "Where do I go when I am stuck on something in this domain?"),
    ("deploy", "path_to_prod", "How does a change I make reach production?"),
    ("gates", "path_to_prod", "What has to happen before my change can be promoted?"),
    ("hazards", "hazards", "What is most likely to break for someone new to this domain?"),
    ("never", "hazards", "What should I never do here, and why?"),
    ("integrations", "orientation", "What other systems does {domain} depend on?"),
)

_REPO_QUESTION = ("repo-setup", "runnable",
                  "How do I get the {repo} repository running locally?")

_JUDGE_PROMPT = """You are checking whether a domain's onboarding context is \
sufficient for a new engineer's first week.

Below is the ENTIRE context that domain provides, followed by numbered \
questions. For each question decide, using ONLY the context:

- "answered"  - the context clearly answers it
- "partial"   - the context gestures at it but a newcomer would still be stuck
- "missing"   - the context does not answer it

Do not use outside knowledge, and do not be generous: a plausible guess is \
"missing". Reply with JSON only, an array of objects with keys "n" (the \
question number), "verdict", and "why" (at most 15 words).

CONTEXT
-------
{context}

QUESTIONS
---------
{questions}
"""


def build_questions(domain: str, product: str = "", repos: Optional[list[dict]] = None) -> list[Question]:
    """The exam for one domain: fixed bank plus a question per linked repo."""
    values = {"domain": domain or "this domain", "product": product or (domain or "the product")}
    questions = [
        Question(key, area, text.format(**values, repo=""))
        for key, area, text in _BANK
    ]
    key, area, text = _REPO_QUESTION
    for repo in (repos or [])[:MAX_REPO_QUESTIONS]:
        slug = repo.get("slug") or repo.get("repo_slug") or ""
        if slug:
            questions.append(Question(f"{key}:{slug}", area, text.format(repo=slug, **values)))
    return questions


def render_context(stamps_text: dict[str, str]) -> str:
    """Assemble the finalized context files into one document for the judge."""
    parts = []
    for name in sorted(stamps_text):
        body = (stamps_text[name] or "").strip()
        if body:
            parts.append(f"## {name}\n{body}")
    return "\n\n".join(parts)


def judge(questions: list[Question], context: str, provider: Any) -> Optional[Report]:
    """Score the context against the questions. ``None`` when the judge is unusable.

    Every failure path returns ``None`` rather than a low score: an empty
    context, a provider that raises, an unparseable reply. Each of those is a
    statement about our tooling, not about the domain.
    """
    if not questions or not context.strip() or provider is None:
        return None

    numbered = "\n".join(f"{i + 1}. {q.text}" for i, q in enumerate(questions))
    prompt = _JUDGE_PROMPT.format(context=context[:60_000], questions=numbered)

    try:
        raw = provider.generate(prompt)
    except Exception:  # noqa: BLE001 - a judge failure is not a domain failure
        return None

    parsed = _parse(raw, questions)
    if parsed is None:
        return None

    model = ""
    try:
        model = provider.get_name()
    except Exception:  # noqa: BLE001
        pass
    return Report(verdicts=parsed, model=model)


def _parse(raw: str, questions: list[Question]) -> Optional[list[Verdict]]:
    """Read the judge's JSON, tolerating fenced or prose-wrapped replies."""
    if not raw:
        return None
    text = raw.strip()
    fence = re.search(r"```(?:json)?\s*(.+?)```", text, re.DOTALL)
    if fence:
        text = fence.group(1).strip()
    else:
        start, end = text.find("["), text.rfind("]")
        if start != -1 and end > start:
            text = text[start:end + 1]

    try:
        data = json.loads(text)
    except (ValueError, TypeError):
        return None
    if not isinstance(data, list) or not data:
        return None

    by_index: dict[int, dict] = {}
    for item in data:
        if not isinstance(item, dict):
            continue
        try:
            index = int(item.get("n"))
        except (TypeError, ValueError):
            continue
        by_index[index] = item

    verdicts: list[Verdict] = []
    for i, question in enumerate(questions, start=1):
        item = by_index.get(i)
        # A question the judge skipped is unanswered evidence, not a free pass.
        verdict = str((item or {}).get("verdict", "")).strip().lower()
        if verdict not in _WEIGHTS:
            verdict = MISSING
        verdicts.append(Verdict(question, verdict, str((item or {}).get("why", ""))[:120]))

    # A reply that matched nothing is a parse failure wearing a score.
    if all(v.verdict == MISSING for v in verdicts) and not by_index:
        return None
    return verdicts


__all__ = [
    "ANSWERED", "PARTIAL", "MISSING", "MAX_REPO_QUESTIONS",
    "Question", "Verdict", "Report", "build_questions", "render_context",
    "judge",
]
